<a href="https://colab.research.google.com/github/makropolecenia/Book/blob/master/OXFORD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#https://www.bsg.ox.ac.uk/research/research-projects/covid-19-government-response-tracker

In [ ]:
#https://www.bsg.ox.ac.uk/research/research-projects/covid-19-government-response-tracker#data

API

In [ ]:
#https://covidtracker.bsg.ox.ac.uk/about-api

In [ ]:
This endpoint provides JSON by with country stringency data, confirmed cases and deaths on a day by day basis as collected by our data collection team.

In [ ]:
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/date-range/{YYYY-MM-DD}/{YYYY-MM-DD}
where last two values represent start and end dates

In [ ]:
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/{ALPHA-3}/{YYYY-MM-DD}
where last two values represent an ISO 3166-1 alpha-3 country code and a date

API / użycie POSTMANA - TESTY

In [ ]:
#https://stackoverflow.com/questions/32400867/pandas-read-csv-from-url
import pandas as pd
import io
import requests

url = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/date-range/2021-02-01/2021-04-07'
s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))

print(c)
c

Empty DataFrame
Columns: [{"scale":{"deaths":{"min":0, max:559696}, casesConfirmed:{"min":0, max:30922386}, stringency:{"min":0, max:100}}, countries:["ABW", AFG, AGO, ALB, AND, ARE, ARG, AUS, AUT, AZE, BDI, BEL, BEN, BFA, BGD, BGR, BHR, BHS, BIH, BLR, BLZ, BMU, BOL, BRA, BRB, BRN, BTN, BWA, CAF, CAN, CHE, CHL, CHN, CIV, CMR, COD, COG, COL, CPV, CRI, CUB, CYP, CZE, DEU, DJI, DMA, DNK, DOM, DZA, ECU, EGY, ERI, ESP, EST, ETH, FIN, FJI, FRA, FRO, GAB, GBR, GEO, GHA, GIN, GMB, GRC, GRL, GTM, GUM, GUY, HKG, HND, HRV, HTI, HUN, IDN, IND, IRL, IRN, IRQ, ISL, ISR, ITA, JAM, JOR, JPN, KAZ, KEN, KGZ, KHM, KIR, KOR, KWT, LAO, ...]
Index: []

[0 rows x 96284 columns]

Empty DataFrame
Columns: [{"scale":{"deaths":{"min":0, max:559696}, casesConfirmed:{"min":0, max:30922386}, stringency:{"min":0, max:100}}, countries:["ABW", AFG, AGO, ALB, AND, ARE, ARG, AUS, AUT, AZE, BDI, BEL, BEN, BFA, BGD, BGR, BHR, BHS, BIH, BLR, BLZ, BMU, BOL, BRA, BRB, BRN, BTN, BWA, CAF, CAN, CHE, CHL, CHN, CIV, CMR, COD, COG, COL, CPV, CRI, CUB, CYP, CZE, DEU, DJI, DMA, DNK, DOM, DZA, ECU, EGY, ERI, ESP, EST, ETH, FIN, FJI, FRA, FRO, GAB, GBR, GEO, GHA, GIN, GMB, GRC, GRL, GTM, GUM, GUY, HKG, HND, HRV, HTI, HUN, IDN, IND, IRL, IRN, IRQ, ISL, ISR, ITA, JAM, JOR, JPN, KAZ, KEN, KGZ, KHM, KIR, KOR, KWT, LAO, ...]
Index: []

[0 rows x 96284 columns]

In [ ]:
#https://stackoverflow.com/questions/32400867/pandas-read-csv-from-url
import pandas as pd
import io
import requests

url = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/122/2021-05-27'

s=requests.get(url).content
c=pd.read_csv(io.StringIO(s.decode('utf-8')))

print(c)
c

Empty DataFrame
Columns: [{"policyActions":[{"policy_type_code":"NONE", policy_type_display:"No data.  Data may be inferred for last 7 days.", flag_value_display_field:"", policy_value_display_field:"No data.  Data may be inferred for last 7 days.", policyvalue:0, flagged:null, notes:null}], stringencyData:{"msg":"Data unavailable"}}]
Index: []

Empty DataFrame
Columns: [{"policyActions":[{"policy_type_code":"NONE", policy_type_display:"No data.  Data may be inferred for last 7 days.", flag_value_display_field:"", policy_value_display_field:"No data.  Data may be inferred for last 7 days.", policyvalue:0, flagged:null, notes:null}], stringencyData:{"msg":"Data unavailable"}}]
Index: []

In [ ]:
CSV

In [ ]:
#https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv

GITHUB ADRSY DO ZMIESZCZONYCH PLIKÓW CSV

In [ ]:
#https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/codebook.md

In [ ]:
#https://github.com/OxCGRT/covid-policy-tracker

In [ ]:
https://github.com/OxCGRT/covid-policy-tracker/tree/master/data

In [ ]:
##DANE AKTUALIZOWANE 

OxCGRT_latest.csv
OxCGRT Data Update
1 hour ago
OxCGRT_latest_allchanges.csv
OxCGRT Data Update
1 hour ago
OxCGRT_latest_combined.csv
OxCGRT Data Update
1 hour ago
OxCGRT_latest_responses.csv
OxCGRT Data Update
1 hour ago
OxCGRT_latest_withnotes.csv
OxCGRT Data Update

In [ ]:
https://github.com/OxCGRT/covid-policy-tracker/tree/master/data/timeseries

In [ ]:

##SERIE CZASOWE AKTUALIZOWANE 

OxCGRT_timeseries_all.xlsx
OxCGRT Graphs and timeseries Update
18 hours ago
c1_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c1_school_closing.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c2_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c2_workplace_closing.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c3_cancel_public_events.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c3_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c4_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c4_restrictions_on_gatherings.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c5_close_public_transport.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c5_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c6_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c6_stay_at_home_requirements.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c7_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c7_movementrestrictions.csv
OxCGRT Graphs and timeseries Update
18 hours ago
c8_internationaltravel.csv
OxCGRT Graphs and timeseries Update
18 hours ago
confirmed_cases.csv
OxCGRT Graphs and timeseries Update
18 hours ago
confirmed_deaths.csv
OxCGRT Graphs and timeseries Update
18 hours ago
containment_health_index.csv
OxCGRT Graphs and timeseries Update
18 hours ago
e1_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
e1_income_support.csv
OxCGRT Graphs and timeseries Update
18 hours ago
e2_debtrelief.csv
OxCGRT Graphs and timeseries Update
18 hours ago
economic_support_index.csv
OxCGRT Graphs and timeseries Update
18 hours ago
government_response_index.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h1_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h1_public_information_campaigns.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h2_testing_policy.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h3_contact_tracing.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h6_facial_coverings.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h6_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h7_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h7_vaccination_policy.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h8_flag.csv
OxCGRT Graphs and timeseries Update
18 hours ago
h8_protection_of_elderly_people.csv
OxCGRT Graphs and timeseries Update
18 hours ago
stringency_index.csv
OxCGRT Graphs and timeseries Update

WCZYTANIE CSV Z GITHUBA - TEST OK

In [ ]:
import pandas as pd

# DANE AKTUALIZOWANE

#data_url = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/tree/master/data/OxCGRT_latest.csv'

#data/OxCGRT_latest.csv  OK działa

data_url = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/OxCGRT_latest.csv'

data = pd.read_csv(data_url)

print(data.head())

data

  CountryName CountryCode  ... EconomicSupportIndex EconomicSupportIndexForDisplay
0       Aruba         ABW  ...                  0.0                            0.0
1       Aruba         ABW  ...                  0.0                            0.0
2       Aruba         ABW  ...                  0.0                            0.0
3       Aruba         ABW  ...                  0.0                            0.0
4       Aruba         ABW  ...                  0.0                            0.0

[5 rows x 51 columns]

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

       CountryName  ... EconomicSupportIndexForDisplay
0            Aruba  ...                            0.0
1            Aruba  ...                            0.0
2            Aruba  ...                            0.0
3            Aruba  ...                            0.0
4            Aruba  ...                            0.0
...            ...  ...                            ...
144429    Zimbabwe  ...                            0.0
144430    Zimbabwe  ...                            0.0
144431    Zimbabwe  ...                            0.0
144432    Zimbabwe  ...                            0.0
144433    Zimbabwe  ...                            0.0

[144434 rows x 51 columns]

In [ ]:
import pandas as pd


#SERIE CZASOWE AKTUALIZOWANE 

#data/timeseries/c1_flag.csv

#data_url = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/tree/master/data/timeseries/c1_flag.csv'

data_url = 'https://raw.githubusercontent.com/OxCGRT/covid-policy-tracker/master/data/timeseries/c1_flag.csv'


data = pd.read_csv(data_url)

print(data.head())

data

   Unnamed: 0 country_code country_name  ...  25May2021  26May2021  27May2021
0           1          ABW        Aruba  ...        NaN        NaN        NaN
1           2          AFG  Afghanistan  ...        NaN        NaN        NaN
2           3          AGO       Angola  ...        NaN        NaN        NaN
3           4          ALB      Albania  ...        1.0        1.0        1.0
4           5          AND      Andorra  ...        NaN        NaN        NaN

[5 rows x 516 columns]

     Unnamed: 0 country_code  country_name  ...  25May2021  26May2021  27May2021
0             1          ABW         Aruba  ...        NaN        NaN        NaN
1             2          AFG   Afghanistan  ...        NaN        NaN        NaN
2             3          AGO        Angola  ...        NaN        NaN        NaN
3             4          ALB       Albania  ...        1.0        1.0        1.0
4             5          AND       Andorra  ...        NaN        NaN        NaN
..          ...          ...           ...  ...        ...        ...        ...
181         182          VUT       Vanuatu  ...        NaN        NaN        NaN
182         183          YEM         Yemen  ...        NaN        NaN        NaN
183         184          ZAF  South Africa  ...        NaN        NaN        NaN
184         185          ZMB        Zambia  ...        NaN        NaN        NaN
185         186          ZWE      Zimbabwe  ...        NaN        NaN        NaN

[186 rows x 516 columns]