<a href="https://colab.research.google.com/github/makropolecenia/Book/blob/master/PAIR1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 29.06.2021

In [1]:
import pandas as pd
from datetime import datetime

In [2]:
df = pd.read_json(path_or_buf = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-06-20', orient = 'index')

In [3]:
#petla podstawiajaca pod url kraje 

for x in country_codes.keys():

  print ( "https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/"+str (x)+"/2021-06-20")

  #print(x)

In [ ]:
#petla podstawiajaca pod url kraje i daty  

for x in country_codes.keys():

  print ( "https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/"+str (x)+"/2021-06-20")

  #print(x)

In [45]:
#https://stackoverflow.com/questions/1060279/iterating-through-a-range-of-dates-in-python

from datetime import date, timedelta

magazyn1 = []
magazyn2 = []
magazynek = []

start_date = date(2021, 1, 1)
end_date = date(2021, 2, 1)
delta = timedelta(days=1)
while start_date <= end_date:
    ##print(start_date.strftime("%Y-%m-%d"))
    #magazyn .append (data )
    magazyn1 .append (start_date.strftime("%Y-%m-%d"))
    start_date += delta


print (" zawartosc magazynu1 ")
print (magazyn1 )
print (" koniec zawartosci magazynu1 ")



# Using for loop
#for i in list:
    #print(i)

for i in magazyn1 :

  #print ( "https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/"+str (x)+"/2021-06-20")

  #print(x)


  #df = pd.read_json(path_or_buf = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-06-20', orient = 'index')
  #df = pd.read_json(path_or_buf = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/'+str (i), orient = 'index')


  print(i)
  print ( "https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/"+str (i))


  df = pd.read_json(path_or_buf = 'https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/'+str (i), orient = 'index')

###

  if not (df[0][0]['policy_type_code'] == "NONE"):
    c1 = df[0][0]['policyvalue_actual']
    c2 = df[1][0]['policyvalue_actual']
    c3 = df[2][0]['policyvalue_actual']
    c4 = df[3][0]['policyvalue_actual']
    c5 = df[4][0]['policyvalue_actual']
    c6 = df[5][0]['policyvalue_actual']
    c7 = df[6][0]['policyvalue_actual']
    c8 = df[7][0]['policyvalue_actual']
    e1 = df[8][0]['policyvalue_actual']
    e2 = df[9][0]['policyvalue_actual']
    e3 = df[10][0]['policyvalue_actual']
    e4 = df[11][0]['policyvalue_actual']
    h1 = df[12][0]['policyvalue_actual']
    h2 = df[13][0]['policyvalue_actual']
    h3 = df[14][0]['policyvalue_actual']
    h4 = df[15][0]['policyvalue_actual']
    #h5 = df[16][0]['policyvalue_actual']
    #h6 = df[17][0]['policyvalue_actual']
    #h7 = df[18][0]['policyvalue_actual']
    #h8 = df[19][0]['policyvalue_actual']

    policies = {c1, c2, c3, c4, c5, c6, c7, c8, e1, e2, e3, e4, h1, h2, h3, h4, h5, h6, h7}

    data = '2021-02-20'

    policies_indicators = {'31001000000':c1,
                       '31002000000':c2,
                       '31003000000':c3,
                       '31004000000':c4,
                       '31005000000':c5,
                       '31006000000':c6,
                       '31007000000':c7,
                       '31008000000':c8,
                       '32001000000':e1,
                       '32002000000':e2,
                       '32003000000':e3,
                       '32004000000':e4,
                       '33001000000':h1,
                       '33002000000':h2,
                       '33003000000':h3,
                       '33004000000':h4,
                       '33005000000':h5,
                       '31009000000':h6,
                       '33101000000':h7}

    country_codes = {'POL':3,
             'AUT':4,
             'BEL':5,
             'BGR':6,
             'HRV':7,
             'CYP':8,
             'CZE':9,
             'DNK':10,
             'EST':11,
             'FIN':12,
             'FRA':13,
             'GRC':14,
             'ESP':15,
             'NLD':16,
             'IRL':17,
             'LTU':18,
             'LUX':19,
             'LVA':20,
             'MLT':21,
             'DEU':22,
             'PRT':23,
             'ROU':24,
             'SVK':25,
             'SVN':26,
             'SWE':27,
             'HUN':28,
             'GBR':29,
             'ITA':30}

    country_list = country_codes.keys()

    df2 = pd.DataFrame.from_dict(policies_indicators, orient='index')
  
    df2.reset_index(inplace=True)
  
    #df2['id_teryt'] = 3
    df2['id_teryt'] = "test"
    #df2['id_teryt_kod_literowy'] = x
    #df2['id_teryt']=df2['id_teryt_kod_literowy'].map (country_codes )


    data = '2021-06-20'
    
    #df2['data'] = data
    df2['data'] = i
   
    df2=df2.rename(columns = {'index': 'id_wskaznik', 0:'wartosc'} )
    df2['data_wprowadzenia'] = pd.datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)
    df2['data_modyfikacji'] = pd.datetime.now().replace(hour=0,minute=0,second=0,microsecond=0)
    df2['id_komentarz'] = 1
    df2['id_wprowadzajacego'] = 15
    df2['id_modyfikujacego'] = 15
  
    print ("df2")
    print (df2)
 

    magazynek .append (df2 )


print (" zawartosc magazynu2 ")
print (magazynek )
print (" koniec zawartosci magazynu2 ")


datex =pd .concat (magazynek )
print (" połączony magazyn2 ")
print(datex)

df_to_excel =pd .DataFrame (datex )
df_to_excel .to_excel ("API_JEDNA_PETLA_DATA.xlsx")
print (" zakonczenie programu ")

datex

 zawartosc magazynu1
['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01']
 koniec zawartosci magazynu1
2021-01-01
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        2  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-02
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-02
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-03
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-03

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-04
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-04
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-05
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-05

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-06
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-06
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-07
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-07

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-08
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-08
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-09
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-09

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-10
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-10
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-11
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-12
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-12
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-13
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-13

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-14
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-14
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-15
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-15

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-16
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-16
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-17
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-17

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-18
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-18
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-19
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-19

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-20
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-20
df2
    id_wskaznik     wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000           2  ...                 15                15
1   31002000000           2  ...                 15                15
2   31003000000           2  ...                 15                15
3   31004000000           4  ...                 15                15
4   31005000000           1  ...                 15                15
5   31006000000           1  ...                 15                15
6   31007000000           1  ...                 15                15
7   31008000000           3  ...                 15                15
8   32001000000           2  ...                 15                15
9   32002000000           1  ...                 15                15
10  32003000000  2302990000  ...                 15                15
11  32004000000           0  ...                 15                15
12  33001000000           2  ...                 15                15
13  33002000000           2  ...                 15                15
14  33003000000           1  ...                 15                15
15  33004000000           0  ...                 15                15
16  33005000000           0  ...                 15                15
17  31009000000           2  ...                 15                15
18  33101000000           5  ...                 15                15

[19 rows x 9 columns]
2021-01-21
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-21

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-22
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-22
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-23
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-23

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-24
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-24
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-25
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-25

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-26
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-26
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-27
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-27

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-28
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-28
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-29
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-29

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-30
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-30

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-01-31
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-01-31
df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
2021-02-01
https://covidtrackerapi.bsg.ox.ac.uk/api/v2/stringency/actions/POL/2021-02-01

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:141: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:142: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.

df2
    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        2  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns]
 zawartosc magazynu2
[    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        2  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15
12  33001000000        2  ...                 15                15
13  33002000000        2  ...                 15                15
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[19 rows x 9 columns],     id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
5   31006000000        1  ...                 15                15
6   31007000000        1  ...                 15                15
7   31008000000        3  ...                 15                15
8   32001000000        2  ...                 15                15
9   32002000000        1  ...                 15                15
10  32003000000        0  ...                 15                15
11  32004000000        0  ...                 15                15

    id_wskaznik  wartosc  ... id_wprowadzajacego id_modyfikujacego
0   31001000000        3  ...                 15                15
1   31002000000        2  ...                 15                15
2   31003000000        2  ...                 15                15
3   31004000000        4  ...                 15                15
4   31005000000        1  ...                 15                15
..          ...      ...  ...                ...               ...
14  33003000000        1  ...                 15                15
15  33004000000        0  ...                 15                15
16  33005000000        0  ...                 15                15
17  31009000000        2  ...                 15                15
18  33101000000        5  ...                 15                15

[608 rows x 9 columns]