<a href="https://colab.research.google.com/github/makropolecenia/Book/blob/master/wordometer4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TESTY Z DNIA 28.05.2021

BIBLIOTEKA WORDOMETER TESTY

In [ ]:
#https://pypi.org/project/worldometer/ #działa

In [ ]:
pip install worldometer

Collecting worldometer
  Downloading https://files.pythonhosted.org/packages/99/91/5aee9e3e42a167eaef6fd01fc4b01e8d91c52c420260d3b143b7f3110c61/worldometer-1.0.1-py3-none-any.whl
Collecting requests-html
  Downloading https://files.pythonhosted.org/packages/24/bc/a4380f09bab3a776182578ce6b2771e57259d0d4dbce178205779abdc347/requests_html-0.10.0-py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from requests-html->worldometer) (2.23.0)
Collecting fake-useragent
  Downloading https://files.pythonhosted.org/packages/d1/79/af647635d6968e2deb57a208d309f6069d31cb138066d7e821e575112a80/fake-useragent-0.1.11.tar.gz
Collecting pyppeteer>=0.0.14
  Downloading https://files.pythonhosted.org/packages/4a/05/ea3250282e46fda60df1f1d5246bb8cdc022abb89969c61a98ea28fd6b82/pyppeteer-0.2.5-py3-none-any.whl (87kB)
     |████████████████████████████████| 92kB 2.8MB/s
Collecting parse
  Downloading https://files.pythonhosted.org/packages/89/a1/82ce536be577ba09d4dcee45db58423a180873ad38a2d014d26ab7b7cb8a/parse-1.19.0.tar.gz
Collecting w3lib
  Downloading https://files.pythonhosted.org/packages/a3/59/b6b14521090e7f42669cafdb84b0ab89301a42f1f1a82fcf5856661ea3a7/w3lib-1.22.0-py2.py3-none-any.whl
Collecting pyquery
  Downloading https://files.pythonhosted.org/packages/58/0b/85d15e21f660a8ea68b1e0286168938857391f4ec9f6d204d91c9e013826/pyquery-1.4.3-py3-none-any.whl
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->worldometer) (0.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (3.0.4)
Collecting importlib-metadata<3.0.0,>=2.1.1; python_version < "3.8"
  Downloading https://files.pythonhosted.org/packages/98/b8/8ec57a8ef46fbe7f185318c7ff7df9a06c9df451d9a59a067bfa851bb828/importlib_metadata-2.1.1-py2.py3-none-any.whl
Collecting websockets<9.0,>=8.1
  Downloading https://files.pythonhosted.org/packages/5a/0b/3ebc752392a368af14dd24ee041683416ac6d2463eead94b311b11e41c82/websockets-8.1-cp37-cp37m-manylinux2010_x86_64.whl (79kB)
     |████████████████████████████████| 81kB 6.5MB/s
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->worldometer) (1.4.4)
Collecting pyee<9.0.0,>=8.1.0
  Downloading https://files.pythonhosted.org/packages/0d/0a/933b3931107e1da186963fd9bb9bceb9a613cff034cb0fb3b0c61003f357/pyee-8.1.0-py2.py3-none-any.whl
Collecting tqdm<5.0.0,>=4.42.1
  Downloading https://files.pythonhosted.org/packages/42/d7/f357d98e9b50346bcb6095fe3ad205d8db3174eb5edb03edfe7c4099576d/tqdm-4.61.0-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 8.1MB/s
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from w3lib->requests-html->worldometer) (1.14.0)
Collecting cssselect>0.7.9
  Downloading https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->worldometer) (4.5.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->worldometer) (4.8.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata<3.0.0,>=2.1.1; python_version < "3.8"->pyppeteer>=0.0.14->requests-html->worldometer) (3.4.1)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.7/dist-packages (from beautifulsoup4->bs4->requests-html->worldometer) (2.0)
Building wheels for collected packages: fake-useragent, parse
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-cp37-none-any.whl size=13485 sha256=8f27deb06deccaa40b2835eee209ec4544be8035c2b3000e6301fe755001a963
  Stored in directory: /root/.cache/pip/wheels/5e/63/09/d1dc15179f175357d3f5c00cbffbac37f9e8690d80545143ff
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-cp37-none-any.whl size=24581 sha256=27e58332f79b12424d84be679a050aa6282cbe5c37a3607edc8f152a91444d1c
  Stored in directory: /root/.cache/pip/wheels/c0/39/ea/e2fd678bd130953f5438470b8dfa529f00787e9b8b92b27467
Successfully built fake-useragent parse
Installing collected packages: fake-useragent, importlib-metadata, websockets, pyee, tqdm, pyppeteer, parse, w3lib, cssselect, pyquery, requests-html, worldometer
  Found existing installation: importlib-metadata 4.0.1
    Uninstalling importlib-metadata-4.0.1:
      Successfully uninstalled importlib-metadata-4.0.1
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1
Successfully installed cssselect-1.1.0 fake-useragent-0.1.11 importlib-metadata-2.1.1 parse-1.19.0 pyee-8.1.0 pyppeteer-0.2.5 pyquery-1.4.3 requests-html-0.10.0 tqdm-4.61.0 w3lib-1.22.0 websockets-8.1 worldometer-1.0.1

In [ ]:
pip install csv

ERROR: Could not find a version that satisfies the requirement csv (from versions: none)
ERROR: No matching distribution found for csv

SCRAPER WORDOMETER ZRZUCA TYLKO DO PLIKU **CSV**

In [ ]:
#https://dev.to/kalebu/how-to-track-coronavirus-spread-using-python-283i

In [ ]:
import csv
import requests
from bs4 import BeautifulSoup

html = requests.get('https://www.worldometers.info/coronavirus/').text
html_soup = BeautifulSoup(html, 'html.parser')
rows = html_soup.find_all('tr')

def extract_text(row, tag):
    element = BeautifulSoup(row, 'html.parser').find_all(tag)
    text = [col.get_text() for col in element]
    return text

heading = rows.pop(0)
heading_row = extract_text(str(heading), 'th')[1:9]

with open('corona.csv', 'w') as store:
    Store = csv.writer(store, delimiter=',')
    Store.writerow(heading_row)
    for row in rows:
        test_data = extract_text(str(row), 'td')[1:9]
        Store.writerow(test_data)

SCRAPER WORDOMETER  PO MODYFIKACJI ZAPISUJE DO DATAFRAME,  ZRZUCA DO PLIKU CSV, ZRZUCA DO PLIKU EXCELA   

---

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
import csv
import requests
from bs4 import BeautifulSoup

html = requests.get('https://www.worldometers.info/coronavirus/').text
html_soup = BeautifulSoup(html, 'html.parser')
rows = html_soup.find_all('tr')

def extract_text(row, tag):
    element = BeautifulSoup(row, 'html.parser').find_all(tag)
    text = [col.get_text() for col in element]
    return text

heading = rows.pop(0)
heading_row = extract_text(str(heading), 'th')[1:9]

with open('corona.csv', 'w') as store:
    Store = csv.writer(store, delimiter=',')
    Store.writerow(heading_row)
    for row in rows:
        test_data = extract_text(str(row), 'td')[1:9]
        Store.writerow(test_data)

# import pandas module 
import pandas as pd 
    
# making dataframe 
df = pd.read_csv("corona.csv") 
   
# output the dataframe
print(df)

df.to_excel("corona_excel.xls")

df
#df.to_csv('data.csv')

         Country,Other   TotalCases  ... NewRecovered ActiveCases
0    \nNorth America\n   39,643,351  ...       +1,912   6,344,837
1             \nAsia\n   50,383,948  ...      +33,445   3,770,467
2    \nSouth America\n   28,312,151  ...       +1,462   2,009,267
3           \nEurope\n   46,439,907  ...      +52,784   2,127,468
4           \nAfrica\n    4,843,104  ...          NaN     350,809
..                 ...          ...  ...          ...         ...
709             Total:   46,356,440  ...     +113,520   2,218,055
710             Total:    4,830,593  ...       +8,886     345,904
711             Total:       67,829  ...          +38       1,350
712             Total:          721  ...          NaN           0
713             Total:  169,079,340  ...     +703,487  14,751,065

[714 rows x 8 columns]

         Country,Other   TotalCases  ... NewRecovered ActiveCases
0    \nNorth America\n   39,643,351  ...       +1,912   6,344,837
1             \nAsia\n   50,383,948  ...      +33,445   3,770,467
2    \nSouth America\n   28,312,151  ...       +1,462   2,009,267
3           \nEurope\n   46,439,907  ...      +52,784   2,127,468
4           \nAfrica\n    4,843,104  ...          NaN     350,809
..                 ...          ...  ...          ...         ...
709             Total:   46,356,440  ...     +113,520   2,218,055
710             Total:    4,830,593  ...       +8,886     345,904
711             Total:       67,829  ...          +38       1,350
712             Total:          721  ...          NaN           0
713             Total:  169,079,340  ...     +703,487  14,751,065

[714 rows x 8 columns]

In [ ]:
pip install worldometer

Collecting worldometer
  Downloading https://files.pythonhosted.org/packages/99/91/5aee9e3e42a167eaef6fd01fc4b01e8d91c52c420260d3b143b7f3110c61/worldometer-1.0.1-py3-none-any.whl
Collecting requests-html
  Downloading https://files.pythonhosted.org/packages/24/bc/a4380f09bab3a776182578ce6b2771e57259d0d4dbce178205779abdc347/requests_html-0.10.0-py3-none-any.whl
Collecting pyppeteer>=0.0.14
  Downloading https://files.pythonhosted.org/packages/4a/05/ea3250282e46fda60df1f1d5246bb8cdc022abb89969c61a98ea28fd6b82/pyppeteer-0.2.5-py3-none-any.whl (87kB)
     |████████████████████████████████| 92kB 2.6MB/s
Collecting pyquery
  Downloading https://files.pythonhosted.org/packages/58/0b/85d15e21f660a8ea68b1e0286168938857391f4ec9f6d204d91c9e013826/pyquery-1.4.3-py3-none-any.whl
Requirement already satisfied: bs4 in /usr/local/lib/python3.7/dist-packages (from requests-html->worldometer) (0.0.1)
Collecting parse
  Downloading https://files.pythonhosted.org/packages/89/a1/82ce536be577ba09d4dcee45db58423a180873ad38a2d014d26ab7b7cb8a/parse-1.19.0.tar.gz
Collecting w3lib
  Downloading https://files.pythonhosted.org/packages/a3/59/b6b14521090e7f42669cafdb84b0ab89301a42f1f1a82fcf5856661ea3a7/w3lib-1.22.0-py2.py3-none-any.whl
Collecting fake-useragent
  Downloading https://files.pythonhosted.org/packages/d1/79/af647635d6968e2deb57a208d309f6069d31cb138066d7e821e575112a80/fake-useragent-0.1.11.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from requests-html->worldometer) (2.23.0)
Collecting tqdm<5.0.0,>=4.42.1
  Downloading https://files.pythonhosted.org/packages/42/d7/f357d98e9b50346bcb6095fe3ad205d8db3174eb5edb03edfe7c4099576d/tqdm-4.61.0-py2.py3-none-any.whl (75kB)
     |████████████████████████████████| 81kB 5.2MB/s
Collecting urllib3<2.0.0,>=1.25.8
  Downloading https://files.pythonhosted.org/packages/0c/cd/1e2ec680ec7b09846dc6e605f5a7709dfb9d7128e51a026e7154e18a234e/urllib3-1.26.5-py2.py3-none-any.whl (138kB)
     |████████████████████████████████| 143kB 23.1MB/s
Collecting websockets<9.0,>=8.1
  Downloading https://files.pythonhosted.org/packages/5a/0b/3ebc752392a368af14dd24ee041683416ac6d2463eead94b311b11e41c82/websockets-8.1-cp37-cp37m-manylinux2010_x86_64.whl (79kB)
     |████████████████████████████████| 81kB 7.2MB/s
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.7/dist-packages (from pyppeteer>=0.0.14->requests-html->worldometer) (1.4.4)
Collecting importlib-metadata<3.0.0,>=2.1.1; python_version < "3.8"
  Downloading https://files.pythonhosted.org/packages/98/b8/8ec57a8ef46fbe7f185318c7ff7df9a06c9df451d9a59a067bfa851bb828/importlib_metadata-2.1.1-py2.py3-none-any.whl
Collecting pyee<9.0.0,>=8.1.0
  Downloading https://files.pythonhosted.org/packages/0d/0a/933b3931107e1da186963fd9bb9bceb9a613cff034cb0fb3b0c61003f357/pyee-8.1.0-py2.py3-none-any.whl
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.7/dist-packages (from pyquery->requests-html->worldometer) (4.2.6)
Collecting cssselect>0.7.9
  Downloading https://files.pythonhosted.org/packages/3b/d4/3b5c17f00cce85b9a1e6f91096e1cc8e8ede2e1be8e96b87ce1ed09e92c5/cssselect-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from bs4->requests-html->worldometer) (4.6.3)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from w3lib->requests-html->worldometer) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (2020.12.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->requests-html->worldometer) (3.0.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata<3.0.0,>=2.1.1; python_version < "3.8"->pyppeteer>=0.0.14->requests-html->worldometer) (3.4.1)
Building wheels for collected packages: parse, fake-useragent
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-cp37-none-any.whl size=24581 sha256=9fc6dd22624230bd1e372697c7f4090b20e022ac1f55b866f53806ed149aa0e7
  Stored in directory: /root/.cache/pip/wheels/c0/39/ea/e2fd678bd130953f5438470b8dfa529f00787e9b8b92b27467
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-cp37-none-any.whl size=13485 sha256=2a2e12225dde73445d597cf7ea1bffb7a318ad0c4d993a36e1208d6a92d65a82
  Stored in directory: /root/.cache/pip/wheels/5e/63/09/d1dc15179f175357d3f5c00cbffbac37f9e8690d80545143ff
Successfully built parse fake-useragent
ERROR: requests 2.23.0 has requirement urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you'll have urllib3 1.26.5 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
Installing collected packages: tqdm, urllib3, websockets, importlib-metadata, pyee, pyppeteer, cssselect, pyquery, parse, w3lib, fake-useragent, requests-html, worldometer
  Found existing installation: tqdm 4.41.1
    Uninstalling tqdm-4.41.1:
      Successfully uninstalled tqdm-4.41.1
  Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Found existing installation: importlib-metadata 4.0.1
    Uninstalling importlib-metadata-4.0.1:
      Successfully uninstalled importlib-metadata-4.0.1
Successfully installed cssselect-1.1.0 fake-useragent-0.1.11 importlib-metadata-2.1.1 parse-1.19.0 pyee-8.1.0 pyppeteer-0.2.5 pyquery-1.4.3 requests-html-0.10.0 tqdm-4.61.0 urllib3-1.26.5 w3lib-1.22.0 websockets-8.1 worldometer-1.0.1






 Strona OURWOLDINDATA.ORG pobiera ze żródła https://github.com/CSSEGISandData/COVID-19 COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University

In [ ]:
#https://blogs.ed.ac.uk/mnaylor/2018/10/07/web-scraping-in-python/

In [ ]:
#https://stackoverflow.com/questions/67161509/python-how-can-i-download-csv-dataset-from-ourworldindata-org-in-google-colab

In [ ]:
https://github.com/owid/covid-19-data/tree/master/public/data 
#Data on COVID-19 (coronavirus) by Our World in Data

In [ ]:
#próba pobrania całej bazy

In [ ]:
import pandas as pd

#url='https://aqicn.org/data-platform/covid19/report/15682-12b6284e/2020
url='https://github.com/owid/covid-19-data/tree/master/public/data' 

#url = 'https://raw.githubusercontent.com/owid/covid-19-data/tree/master/public/data.csv'

df = pd.read_csv(url, skiprows=1) 
#df = pd.read_csv(url)

print ("załadowano!!!")
df

ParserError: ignored

ZE STRONY GITHUB COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University

In [ ]:
#szeregi czasowe

In [ ]:
#https://github.com/CSSEGISandData/COVID-19/tree/master/archived_data/archived_time_series # archiwalne

In [ ]:
#dostępne serie danych do wklejenia w kod # archiwalne

In [ ]:
time_series_19-covid-Confirmed_archived_0325.csv
archived_0325
14 months ago
time_series_19-covid-Deaths_archived_0325.csv
archived_0325
14 months ago
time_series_19-covid-Recovered_archived_0325.csv
archived_0325
14 months ago
time_series_2019-ncov-Confirmed.csv
update
16 months ago
time_series_2019-ncov-Deaths.csv
update
16 months ago
time_series_2019-ncov-Recovered.csv

In [ ]:
https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data #aktualizowane

In [ ]:
#dostępne serie danych do wklejenia w kod #  aktualizowane

In [ ]:
time_series_covid19_confirmed_global.csv

In [ ]:
#przekształcenie URL aby pobrał zawartość pliku CSV

In [ ]:
#https://stackoverflow.com/questions/63521790/parsererror-error-tokenizing-data-c-error-expected-1-fields-in-line-32-saw-2

import pandas as pd

data_url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'  

data = pd.read_csv(data_url)

print(data.head())

data

  Province/State Country/Region       Lat  ...  5/25/21  5/26/21  5/27/21
0            NaN    Afghanistan  33.93911  ...    66903    67743    68366
1            NaN        Albania  41.15330  ...   132229   132244   132264
2            NaN        Algeria  28.03390  ...   127361   127646   127926
3            NaN        Andorra  42.50630  ...    13664    13671    13682
4            NaN         Angola -11.20270  ...    32933    33338    33607

[5 rows x 496 columns]

    Province/State      Country/Region        Lat  ...  5/25/21  5/26/21  5/27/21
0              NaN         Afghanistan  33.939110  ...    66903    67743    68366
1              NaN             Albania  41.153300  ...   132229   132244   132264
2              NaN             Algeria  28.033900  ...   127361   127646   127926
3              NaN             Andorra  42.506300  ...    13664    13671    13682
4              NaN              Angola -11.202700  ...    32933    33338    33607
..             ...                 ...        ...  ...      ...      ...      ...
271            NaN             Vietnam  14.058324  ...     5931     6086     6356
272            NaN  West Bank and Gaza  31.952200  ...   306334   306795   306795
273            NaN               Yemen  15.552727  ...     6670     6688     6696
274            NaN              Zambia -13.133897  ...    93428    93627    93947
275            NaN            Zimbabwe -19.015438  ...    38706    38819    38854

[276 rows x 496 columns]

ZE STRONY OUR WOLD IN DATA INNE DANE PRZYKŁAD

In [ ]:
#https://blogs.ed.ac.uk/mnaylor/2018/10/07/web-scraping-in-python/

df_list = pd.read_html( "https://ourworldindata.org/ofdacred-international-disaster-data" )

df_table1 = df_list[0]

df_table1

   Yearly average global annual deaths from natural disasters, by decade  ...  Wildfire
0                                               1900s                     ...         0
1                                               1910s                     ...       107
2                                               1920s                     ...        10
3                                               1930s                     ...         7
4                                               1940s                     ...        25
5                                               1950s                     ...         1
6                                               1960s                     ...         7
7                                               1970s                     ...         1
8                                               1980s                     ...        40
9                                               1990s                     ...        86
10                                              2000s                     ...        63
11                                              2010s                     ...        52

[12 rows x 11 columns]

In [ ]:
#dane covidowe dostepne w zrodle - spis

In [ ]:
#https://ourworldindata.org/charts?search=covid

In [ ]:
Coronavirus disease [COVID-19]
Biweekly change in confirmed COVID-19 cases
Biweekly change in confirmed COVID-19 deaths
Biweekly confirmed COVID-19 cases
Biweekly confirmed COVID-19 cases per million people
Biweekly confirmed COVID-19 deaths
Biweekly confirmed COVID-19 deaths per million people
COVID-19 Testing Policies
COVID-19 Vaccination Policy
COVID-19 death rate vs. Population density
COVID-19 vaccine doses administered
COVID-19 vaccine doses administered per 100 people
COVID-19: Containment and Health Index
COVID-19: Daily new confirmed cases vs cumulative cases
COVID-19: Daily new confirmed cases vs cumulative cases
COVID-19: Daily tests vs. Daily new confirmed cases
COVID-19: Daily tests vs. Daily new confirmed cases per million
COVID-19: Stringency Index
Cancellation of public events during COVID-19 pandemic
Case fatality rate of COVID-19 vs. Median age of the population
Case fatality rate of the ongoing COVID-19 pandemic
Case fatality rate vs. Total confirmed COVID-19 deaths
Confirmed COVID-19 deaths per million vs GDP per capita
Confirmed COVID-19 deaths vs. Population density
Cumulative COVID-19 tests, confirmed cases and deaths
Cumulative COVID-19 tests, confirmed cases and deaths per million people
Cumulative confirmed COVID-19 casesMap and country time-series
Cumulative confirmed COVID-19 casesBy Region
Cumulative confirmed COVID-19 cases per million vs. GDP per capita
Cumulative confirmed COVID-19 deathsBy Region
Cumulative confirmed COVID-19 deaths and cases
Cumulative confirmed COVID-19 deaths vs. cases
Daily COVID-19 tests
Daily COVID-19 tests
Daily COVID-19 tests per thousand people
Daily COVID-19 tests per thousand peopleRolling 7-day average
Daily COVID-19 vaccine doses administered
Daily COVID-19 vaccine doses administered per 100 people
Daily and total confirmed COVID-19 deaths
Daily and total confirmed COVID-19 deaths per million
Daily confirmed COVID-19 casesMap and country time-series
Daily confirmed COVID-19 casesStacked area chart – by world region
Daily confirmed COVID-19 cases and deaths
Daily confirmed COVID-19 cases per million people
Daily confirmed COVID-19 cases per million, 3-day rolling average
Daily confirmed COVID-19 cases per million: which countries are bending the curve?Trajectories
Daily confirmed COVID-19 cases, rolling 7-day average
Daily confirmed COVID-19 cases: which countries are bending the curve?
Daily confirmed COVID-19 deathsMap and time-series
Daily confirmed COVID-19 deathsBy Region
Daily confirmed COVID-19 deaths per million people
Daily confirmed COVID-19 deaths per million, 3-day rolling average
Daily confirmed COVID-19 deaths per million, rolling 7-day average
Daily confirmed COVID-19 deaths per million: which countries are bending the curve?Trajectories
Daily confirmed COVID-19 deaths, rolling 7-day average
Daily confirmed COVID-19 deaths: which countries are bending the curve?Trajectories
Daily new confirmed COVID-19 cases and deaths
Daily new confirmed cases of COVID-19
Daily new confirmed cases of COVID-19 per million people
Daily new estimated COVID-19 infections from the ICL model
Daily new estimated COVID-19 infections from the IHME model
Daily new estimated COVID-19 infections from the LSHTM model
Daily new estimated COVID-19 infections from the YYG model
Daily new estimated infections of COVID-19
Daily vs. Total confirmed COVID-19 cases
Daily vs. Total confirmed COVID-19 cases per million people
Daily vs. Total confirmed COVID-19 deaths per million
Daily vs. cumulative confirmed deaths due to COVID-19
Debt or contract relief during the COVID-19 pandemic
Excess mortality during COVID-19: Deaths from all causes compared to previous years, all agesP-scores
Excess mortality during COVID-19: Deaths from all causes compared to previous years, by ageP-scores
Excess mortality during COVID-19: Number of deaths from all causes compared to previous yearsRaw death counts
Face covering policies during the COVID-19 pandemic
Government Response Stringency Index vs. Biweekly change in confirmed COVID-19 cases
Income support during the COVID-19 pandemic
International travel controls during the COVID-19 pandemic
Number of COVID-19 patients in ICU per million
Number of COVID-19 patients in hospital
Number of COVID-19 patients in hospital per million
Number of COVID-19 patients in intensive care (ICU)
Number of people fully vaccinated against COVID-19
Number of people who received at least one dose of COVID-19 vaccine
Number of tests per confirmed case vs. Total confirmed COVID-19 cases per million people
Per capita: COVID-19 tests vs. Confirmed deaths
Per capita: tests for COVID-19 vs. Confirmed cases
Public information campaigns on the COVID-19 pandemic
Public transport closures during the COVID-19 pandemic
Restrictions on internal movement during the COVID-19 pandemic
Restrictions on public gatherings in the COVID-19 pandemic
School closures during the COVID-19 pandemic
Share among unvaccinated people who would get a COVID-19 vaccine this week if it was available to them
Share of COVID-19 tests that were positiveOver time, since 5th death was confirmed
Share of people who received at least one dose of COVID-19 vaccine
Share of the population fully vaccinated against COVID-19
Share of total COVID-19 tests that were positive
Stay-at-home requirements during the COVID-19 pandemic
Tests conducted per new confirmed case of COVID-19
Tests per thousand since the 100th confirmed case of COVID-19
Tests per thousand since the 5th confirmed death due to COVID-19
The share of COVID-19 tests that are positive
Total COVID-19 testsLine chart
Total COVID-19 testsMap chart
Total COVID-19 tests conducted vs. Confirmed cases
Total COVID-19 tests conducted vs. Confirmed casesPositive rate comparison
Total COVID-19 tests conducted vs. Confirmed cases per million
Total COVID-19 tests for each confirmed case
Total COVID-19 tests for each confirmed caseBar chart
Total COVID-19 tests per 1,000 peopleLine chart
Total COVID-19 tests per 1,000 peopleMap chart
Total COVID-19 tests per 1,000 peopleBar chart
Total COVID-19 tests per 1,000 vs. GDP per capita
Total COVID-19 tests per 1,000: how are testing rates changing?Since daily new confirmed deaths due to COVID-19 reached 0.1 per million
Total COVID-19 tests per 1,000: how are testing rates changing?Since daily new confirmed deaths due to COVID-19 reached 0.1 per million
Total and daily confirmed COVID-19 cases
Total and daily confirmed COVID-19 cases per million people
Total confirmed COVID-19 casesBy Income Group
Total confirmed COVID-19 cases per million peopleMap and country time-series
Total confirmed COVID-19 cases per million: how rapidly are they increasing?Trajectories
Total confirmed COVID-19 cases vs. deaths per million
Total confirmed COVID-19 cases, by source
Total confirmed COVID-19 cases: how rapidly are they increasing?Trajectories
Total confirmed COVID-19 deathsMap and country time-series
Total confirmed COVID-19 deathsBy Income Group
Total confirmed COVID-19 deaths and cases per million people
Total confirmed COVID-19 deaths per million people
Total confirmed COVID-19 deaths per million vs GDP per capita
Total confirmed COVID-19 deaths per million: how rapidly are they increasing?
Total confirmed COVID-19 deaths: how rapidly are they increasing?Trajectories
Total confirmed deaths due to COVID-19 vs. Population
Total confirmed deaths from COVID-19, by source
Total number of COVID-19 tests per confirmed case
Week by week change in confirmed COVID-19 cases
Week by week change of confirmed COVID-19 cases vs. GDP per capita
Week by week change of confirmed COVID-19 deaths
Week by week change of confirmed COVID-19 deaths vs. GDP per capita
Weekly confirmed COVID-19 cases
Weekly confirmed COVID-19 cases per million people
Weekly confirmed COVID-19 deaths
Weekly confirmed COVID-19 deaths per million people
Weekly new ICU admissions for COVID-19
Weekly new ICU admissions for COVID-19 per million
Weekly new hospital admissions for COVID-19
Weekly new hospital admissions for COVID-19 per million
Which countries do COVID-19 contact tracing?
Workplace closures during the COVID-19 pandemic

ZE STRONY WHO

https://covid19.who.int/

In [ ]:
#https://apps.who.int/gho/data/node.resources.api

In [ ]:
#https://covid19.who.int/

In [ ]:
#https://github.com/devichs/Python-WHO-DataCollection
#https://github.com/devichs/Python-WHO-DataCollection/blob/master/who.py

TESTY PRZYKŁADOWE DANE ZE STRONY WHO

In [ ]:
from bs4 import BeautifulSoup
import requests
import sqlite3

pusta_tabela = []

url = "http://apps.who.int/gho/athena/data/GHO/MDG_0000000016.html?profile=ztable&filter=COUNTRY:*;REGION:*"

r = requests.get(url)
soup = BeautifulSoup(r.text,"html.parser")
GHO = ""
PublishState = ""
Year = ""
Region = ""
Country = ""
DisplayValue = ""
NumbericValue = ""

table = soup.findAll("tr")[1:]
for rows in table:
	cells = rows.findAll("td")
	if len(rows) > 0:
		GHO = cells[0].find(text = True)
		PublishState = cells[1].find(text = True)
		Year = cells[2].find(text = True)
		Region = cells[3].find(text = True)
		Country = cells[4].find(text = True)
		DisplayValue = cells[5].find(text = True)
		NumbericValue = cells[6].find(text = True)
		#pusta_tabela.append(GHO,PublishState,Year,Region,Country,DisplayValue,NumbericValue)
		print(GHO,PublishState,Year,Region,Country,DisplayValue,NumbericValue)
  		
#print(pusta_tabela)

Deaths due to malaria (per 100 000 population) Published 2010 Americas Costa Rica 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Côte d'Ivoire 116.00 116.00000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Democratic People's Republic of Korea 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Democratic Republic of the Congo 119.00 119.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Djibouti 4.40 4.40000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Dominican Republic 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Ecuador 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas El Salvador 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Equatorial Guinea 79.00 79.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Eritrea 5.40 5.40000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Ethiopia 4.00 4.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Gabon 39.00 39.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Gambia 83.00 83.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Georgia 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Ghana 52.00 52.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Guatemala 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Guinea 144.00 144.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Guinea-Bissau 108.00 108.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Guyana 11.00 11.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Haiti 5.70 5.70000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Honduras 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia India 2.40 2.40000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Indonesia 3.60 3.60000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Congo 93.00 93.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Comoros 36.00 36.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Colombia 0.40 0.40000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific China 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Chad 172.00 172.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Central African Republic 169.00 169.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Cabo Verde 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Cameroon 79.00 79.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Cambodia 2.70 2.70000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Burundi 12.00 12.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Burkina Faso 191.00 191.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Brazil 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Botswana 0.90 0.90000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Bolivia (Plurinational State of) 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Bhutan 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Benin 104.00 104.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Belize 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Bangladesh 0.90 0.90000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Azerbaijan 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Armenia 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Argentina 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Angola 64.00 64.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Algeria 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Afghanistan 0.50 0.50000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Iran (Islamic Republic of) 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Philippines 0.20 0.20000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Republic of Korea 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Russian Federation 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Rwanda 4.20 4.20000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Iraq 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Kenya 5.10 5.10000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Kyrgyzstan 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Lao People's Democratic Republic 3.30 3.30000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Liberia 86.00 86.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Madagascar 16.00 16.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Malawi 51.00 51.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Malaysia 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Mali 138.00 138.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Mauritania 22.00 22.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Mexico 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Mozambique 125.00 125.00000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Myanmar 6.80 6.80000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Namibia 0.60 0.60000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Nepal 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Nicaragua 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Niger 100.00 100.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Nigeria 131.00 131.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Oman 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Pakistan 0.90 0.90000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Panama 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Papua New Guinea 44.00 44.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Paraguay 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Peru 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Sao Tome and Principe 29.00 29.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Zimbabwe 62.00 62.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Saudi Arabia 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Senegal 44.00 44.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Sierra Leone 177.00 177.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Solomon Islands 24.00 24.00000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Somalia 26.00 26.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa South Africa 0.20 0.20000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Sri Lanka 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Suriname 0.20 0.20000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Eswatini 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Syrian Arab Republic 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Tajikistan 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Thailand 0.30 0.30000
Deaths due to malaria (per 100 000 population) Published 2010 South-East Asia Timor-Leste 22.00 22.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Togo 63.00 63.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Turkey 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Turkmenistan 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Uganda 52.00 52.00000
Deaths due to malaria (per 100 000 population) Published 2010 Africa United Republic of Tanzania 34.00 34.00000
Deaths due to malaria (per 100 000 population) Published 2010 Europe Uzbekistan 0.00 0.00000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Vanuatu 14.00 14.00000
Deaths due to malaria (per 100 000 population) Published 2010 Americas Venezuela (Bolivarian Republic of) 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Western Pacific Viet Nam 0.10 0.10000
Deaths due to malaria (per 100 000 population) Published 2010 Eastern Mediterranean Yemen 7.20 7.20000
Deaths due to malaria (per 100 000 population) Published 2010 Africa Zambia 67.00 67.00000

BIBLIOTEKA COVID TESTY

In [ ]:
#https://pypi.org/project/covid/

In [ ]:
pip install covid

Collecting covid
  Downloading https://files.pythonhosted.org/packages/07/8c/475557e886f7df6b86365fa13686800a4fb2e9dd77850b47e09144d09fde/covid-2.4.1.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (from covid) (4.6.3)
Collecting pydantic
  Downloading https://files.pythonhosted.org/packages/9f/f2/2d5425efe57f6c4e06cbe5e587c1fd16929dcf0eb90bd4d3d1e1c97d1151/pydantic-1.8.2-cp37-cp37m-manylinux2014_x86_64.whl (10.1MB)
     |████████████████████████████████| 10.1MB 4.1MB/s
Collecting typer
  Downloading https://files.pythonhosted.org/packages/90/34/d138832f6945432c638f32137e6c79a3b682f06a63c488dcfaca6b166c64/typer-0.3.2-py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from covid) (2.23.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pydantic->covid) (3.7.4.3)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /usr/local/lib/python3.7/dist-packages (from typer->covid) (7.1.2)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->covid) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->covid) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->covid) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->covid) (2020.12.5)
Building wheels for collected packages: covid
  Building wheel for covid (PEP 517) ... done
  Created wheel for covid: filename=covid-2.4.1-cp37-none-any.whl size=10419 sha256=ebcb89d54a3d45cfcfd4393898a6ee8f32825af218938b6f28634cb479e8831b
  Stored in directory: /root/.cache/pip/wheels/26/1e/db/d77160690ffc37c4081e75bb59b8ce224c576066e10ceef438
Successfully built covid
Installing collected packages: pydantic, typer, covid
Successfully installed covid-2.4.1 pydantic-1.8.2 typer-0.3.2

COVID TESTY : John Hopkins University API

In [ ]:
#Get All Data
from covid import Covid

covid = Covid()
covid.get_data()
x=covid.get_data()

print(x)

[{'id': '180', 'country': 'US', 'confirmed': 33218607, 'active': None, 'deaths': 593293, 'recovered': None, 'latitude': 40.0, 'longitude': -100.0, 'last_update': 1622197243000}, {'id': '80', 'country': 'India', 'confirmed': 27555457, 'active': 2343152, 'deaths': 318895, 'recovered': 24893410, 'latitude': 20.593684, 'longitude': 78.96288, 'last_update': 1622197243000}, {'id': '24', 'country': 'Brazil', 'confirmed': 16342162, 'active': 1429678, 'deaths': 456674, 'recovered': 14455810, 'latitude': -14.235, 'longitude': -51.9253, 'last_update': 1622197243000}, {'id': '63', 'country': 'France', 'confirmed': 5697081, 'active': 5198644, 'deaths': 109327, 'recovered': 389110, 'latitude': 46.2276, 'longitude': 2.2137, 'last_update': 1622197243000}, {'id': '179', 'country': 'Turkey', 'confirmed': 5220549, 'active': 102764, 'deaths': 46970, 'recovered': 5070815, 'latitude': 38.9637, 'longitude': 35.2433, 'last_update': 1622197243000}, {'id': '144', 'country': 'Russia', 'confirmed': 4986458, 'active': 260796, 'deaths': 118386, 'recovered': 4607276, 'latitude': 61.524, 'longitude': 105.3188, 'last_update': 1622197243000}, {'id': '184', 'country': 'United Kingdom', 'confirmed': 4489552, 'active': 4346052, 'deaths': 128020, 'recovered': 15480, 'latitude': 55.0, 'longitude': -3.0, 'last_update': 1622197243000}, {'id': '86', 'country': 'Italy', 'confirmed': 4205970, 'active': 253193, 'deaths': 125793, 'recovered': 3826984, 'latitude': 41.8719, 'longitude': 12.5674, 'last_update': 1622197243000}, {'id': '67', 'country': 'Germany', 'confirmed': 3676654, 'active': 125332, 'deaths': 88192, 'recovered': 3463130, 'latitude': 51.165691, 'longitude': 10.451526, 'last_update': 1622197243000}, {'id': '7', 'country': 'Argentina', 'confirmed': 3663215, 'active': 367606, 'deaths': 76135, 'recovered': 3219474, 'latitude': -38.4161, 'longitude': -63.6167, 'last_update': 1622197243000}, {'id': '164', 'country': 'Spain', 'confirmed': 3663176, 'active': 3432912, 'deaths': 79888, 'recovered': 150376, 'latitude': 40.463667, 'longitude': -3.74922, 'last_update': 1622197243000}, {'id': '38', 'country': 'Colombia', 'confirmed': 3319193, 'active': 131110, 'deaths': 86693, 'recovered': 3101390, 'latitude': 4.5709, 'longitude': -74.2973, 'last_update': 1622197243000}, {'id': '82', 'country': 'Iran', 'confirmed': 2875858, 'active': 399934, 'deaths': 79384, 'recovered': 2396540, 'latitude': 32.427908, 'longitude': 53.688046, 'last_update': 1622197243000}, {'id': '140', 'country': 'Poland', 'confirmed': 2870595, 'active': 162327, 'deaths': 73557, 'recovered': 2634711, 'latitude': 51.9194, 'longitude': 19.1451, 'last_update': 1622197243000}, {'id': '116', 'country': 'Mexico', 'confirmed': 2405772, 'active': 261601, 'deaths': 222661, 'recovered': 1921510, 'latitude': 23.6345, 'longitude': -102.5528, 'last_update': 1622197243000}, {'id': '182', 'country': 'Ukraine', 'confirmed': 2254674, 'active': 128248, 'deaths': 52252, 'recovered': 2074174, 'latitude': 48.3794, 'longitude': 31.1656, 'last_update': 1622197243000}, {'id': '138', 'country': 'Peru', 'confirmed': 1942054, 'active': -19556, 'deaths': 68816, 'recovered': 1892794, 'latitude': -9.19, 'longitude': -75.0152, 'last_update': 1622197243000}, {'id': '81', 'country': 'Indonesia', 'confirmed': 1803361, 'active': 98704, 'deaths': 50100, 'recovered': 1654557, 'latitude': -0.7893, 'longitude': 113.9213, 'last_update': 1622197243000}, {'id': '126', 'country': 'Netherlands', 'confirmed': 1664708, 'active': 1620088, 'deaths': 17866, 'recovered': 26754, 'latitude': 52.3167, 'longitude': 5.55, 'last_update': 1622197243000}, {'id': '47', 'country': 'Czechia', 'confirmed': 1660481, 'active': 15385, 'deaths': 30088, 'recovered': 1615008, 'latitude': 49.8175, 'longitude': 15.473, 'last_update': 1622197243000}, {'id': '162', 'country': 'South Africa', 'confirmed': 1649977, 'active': 45715, 'deaths': 56170, 'recovered': 1548092, 'latitude': -30.5595, 'longitude': 22.9375, 'last_update': 1622197243000}, {'id': '33', 'country': 'Canada', 'confirmed': 1378993, 'active': 39997, 'deaths': 25393, 'recovered': 1313603, 'latitude': 60.001, 'longitude': -95.001, 'last_update': 1622197243000}, {'id': '36', 'country': 'Chile', 'confirmed': 1352723, 'active': 41353, 'deaths': 28809, 'recovered': 1282561, 'latitude': -35.6751, 'longitude': -71.543, 'last_update': 1622197243000}, {'id': '139', 'country': 'Philippines', 'confirmed': 1209154, 'active': 53770, 'deaths': 20566, 'recovered': 1134818, 'latitude': 12.879721, 'longitude': 121.774017, 'last_update': 1622197243000}, {'id': '83', 'country': 'Iraq', 'confirmed': 1186309, 'active': 71821, 'deaths': 16289, 'recovered': 1098199, 'latitude': 33.223191, 'longitude': 43.679291, 'last_update': 1622197243000}, {'id': '143', 'country': 'Romania', 'confirmed': 1076840, 'active': 10063, 'deaths': 30131, 'recovered': 1036646, 'latitude': 45.9432, 'longitude': 24.9668, 'last_update': 1622197243000}, {'id': '168', 'country': 'Sweden', 'confirmed': 1068473, 'active': 1054022, 'deaths': 14451, 'recovered': None, 'latitude': 60.1282, 'longitude': 18.6435, 'last_update': 1622197243000}, {'id': '17', 'country': 'Belgium', 'confirmed': 1055543, 'active': 1030641, 'deaths': 24902, 'recovered': None, 'latitude': 50.8333, 'longitude': 4.469936, 'last_update': 1622197243000}, {'id': '134', 'country': 'Pakistan', 'confirmed': 913784, 'active': 58611, 'deaths': 20607, 'recovered': 834566, 'latitude': 30.3753, 'longitude': 69.3451, 'last_update': 1622197243000}, {'id': '141', 'country': 'Portugal', 'confirmed': 847006, 'active': 22452, 'deaths': 17022, 'recovered': 807532, 'latitude': 39.3999, 'longitude': -8.2245, 'last_update': 1622197243000}, {'id': '85', 'country': 'Israel', 'confirmed': 839429, 'active': 517, 'deaths': 6406, 'recovered': 832506, 'latitude': 31.046051, 'longitude': 34.851612, 'last_update': 1622197243000}, {'id': '78', 'country': 'Hungary', 'confirmed': 803567, 'active': 84719, 'deaths': 29682, 'recovered': 689166, 'latitude': 47.1625, 'longitude': 19.5033, 'last_update': 1622197243000}, {'id': '14', 'country': 'Bangladesh', 'confirmed': 794985, 'active': 47348, 'deaths': 12480, 'recovered': 735157, 'latitude': 23.685, 'longitude': 90.3563, 'last_update': 1622197243000}, {'id': '88', 'country': 'Japan', 'confirmed': 738919, 'active': 66568, 'deaths': 12775, 'recovered': 659576, 'latitude': 36.204824, 'longitude': 138.252924, 'last_update': 1622197243000}, {'id': '89', 'country': 'Jordan', 'confirmed': 734039, 'active': 11285, 'deaths': 9423, 'recovered': 713331, 'latitude': 31.24, 'longitude': 36.51, 'last_update': 1622197243000}, {'id': '154', 'country': 'Serbia', 'confirmed': 711442, 'active': 704619, 'deaths': 6823, 'recovered': None, 'latitude': 44.0165, 'longitude': 21.0059, 'last_update': 1622197243000}, {'id': '169', 'country': 'Switzerland', 'confirmed': 692111, 'active': 363713, 'deaths': 10798, 'recovered': 317600, 'latitude': 46.8182, 'longitude': 8.2275, 'last_update': 1622197243000}, {'id': '10', 'country': 'Austria', 'confirmed': 643709, 'active': 6306, 'deaths': 10588, 'recovered': 626815, 'latitude': 47.5162, 'longitude': 14.5501, 'last_update': 1622197243000}, {'id': '183', 'country': 'United Arab Emirates', 'confirmed': 563215, 'active': 18528, 'deaths': 1664, 'recovered': 543023, 'latitude': 23.424076, 'longitude': 53.847818, 'last_update': 1622197243000}, {'id': '109', 'country': 'Malaysia', 'confirmed': 549514, 'active': 72823, 'deaths': 2552, 'recovered': 474139, 'latitude': 4.210484, 'longitude': 101.975766, 'last_update': 1622197243000}, {'id': '125', 'country': 'Nepal', 'confirmed': 542256, 'active': 116476, 'deaths': 6951, 'recovered': 418829, 'latitude': 28.1667, 'longitude': 84.25, 'last_update': 1622197243000}, {'id': '99', 'country': 'Lebanon', 'confirmed': 539590, 'active': 16827, 'deaths': 7705, 'recovered': 515058, 'latitude': 33.8547, 'longitude': 35.8623, 'last_update': 1622197243000}, {'id': '122', 'country': 'Morocco', 'confirmed': 518122, 'active': 2780, 'deaths': 9134, 'recovered': 506208, 'latitude': 31.7917, 'longitude': -7.0926, 'last_update': 1622197243000}, {'id': '152', 'country': 'Saudi Arabia', 'confirmed': 445963, 'active': 10152, 'deaths': 7309, 'recovered': 428502, 'latitude': 23.885942, 'longitude': 45.079162, 'last_update': 1622197243000}, {'id': '90', 'country': 'Kazakhstan', 'confirmed': 436931, 'active': 33972, 'deaths': 3435, 'recovered': 399524, 'latitude': 48.0196, 'longitude': 66.9237, 'last_update': 1622197243000}, {'id': '53', 'country': 'Ecuador', 'confirmed': 422329, 'active': 35547, 'deaths': 20357, 'recovered': 366425, 'latitude': -1.8312, 'longitude': -78.1834, 'last_update': 1622197243000}, {'id': '26', 'country': 'Bulgaria', 'confirmed': 417819, 'active': 21026, 'deaths': 17637, 'recovered': 379156, 'latitude': 42.7339, 'longitude': 25.4858, 'last_update': 1622197243000}, {'id': '69', 'country': 'Greece', 'confirmed': 396970, 'active': 291251, 'deaths': 11955, 'recovered': 93764, 'latitude': 39.0742, 'longitude': 21.8243, 'last_update': 1622197243000}, {'id': '16', 'country': 'Belarus', 'confirmed': 390203, 'active': 6715, 'deaths': 2811, 'recovered': 380677, 'latitude': 53.7098, 'longitude': 27.9534, 'last_update': 1622197243000}, {'id': '158', 'country': 'Slovakia', 'confirmed': 389440, 'active': 121807, 'deaths': 12333, 'recovered': 255300, 'latitude': 48.669, 'longitude': 19.699, 'last_update': 1622197243000}, {'id': '135', 'country': 'Panama', 'confirmed': 376237, 'active': 6058, 'deaths': 6361, 'recovered': 363818, 'latitude': 8.538, 'longitude': -80.7821, 'last_update': 1622197243000}, {'id': '21', 'country': 'Bolivia', 'confirmed': 361580, 'active': 59162, 'deaths': 14312, 'recovered': 288106, 'latitude': -16.2902, 'longitude': -63.5887, 'last_update': 1622197243000}, {'id': '44', 'country': 'Croatia', 'confirmed': 355296, 'active': 2968, 'deaths': 7981, 'recovered': 344347, 'latitude': 45.1, 'longitude': 15.2, 'last_update': 1622197243000}, {'id': '137', 'country': 'Paraguay', 'confirmed': 345357, 'active': 52770, 'deaths': 8800, 'recovered': 283787, 'latitude': -23.4425, 'longitude': -58.4438, 'last_update': 1622197243000}, {'id': '66', 'country': 'Georgia', 'confirmed': 341894, 'active': 12741, 'deaths': 4727, 'recovered': 324426, 'latitude': 42.3154, 'longitude': 43.3569, 'last_update': 1622197243000}, {'id': '178', 'country': 'Tunisia', 'confirmed': 340250, 'active': 28468, 'deaths': 12451, 'recovered': 299331, 'latitude': 33.886917, 'longitude': 9.537499, 'last_update': 1622197243000}, {'id': '11', 'country': 'Azerbaijan', 'confirmed': 333317, 'active': 5620, 'deaths': 4891, 'recovered': 322806, 'latitude': 40.1431, 'longitude': 47.5769, 'last_update': 1622197243000}, {'id': '42', 'country': 'Costa Rica', 'confirmed': 311922, 'active': 68076, 'deaths': 3929, 'recovered': 239917, 'latitude': 9.7489, 'longitude': -83.7534, 'last_update': 1622197243000}, {'id': '190', 'country': 'West Bank and Gaza', 'confirmed': 306795, 'active': 3753, 'deaths': 3483, 'recovered': 299559, 'latitude': 31.9522, 'longitude': 35.2332, 'last_update': 1622197243000}, {'id': '95', 'country': 'Kuwait', 'confirmed': 304199, 'active': 13077, 'deaths': 1755, 'recovered': 289367, 'latitude': 29.31166, 'longitude': 47.481766, 'last_update': 1622197243000}, {'id': '52', 'country': 'Dominican Republic', 'confirmed': 288034, 'active': 45915, 'deaths': 3620, 'recovered': 238499, 'latitude': 18.7357, 'longitude': -70.1627, 'last_update': 1622197243000}, {'id': '185', 'country': 'Uruguay', 'confirmed': 280372, 'active': 36997, 'deaths': 4066, 'recovered': 239309, 'latitude': -32.5228, 'longitude': -55.7658, 'last_update': 1622197243000}, {'id': '48', 'country': 'Denmark', 'confirmed': 278142, 'active': 13084, 'deaths': 2512, 'recovered': 262546, 'latitude': 56.2639, 'longitude': 9.5018, 'last_update': 1622197243000}, {'id': '104', 'country': 'Lithuania', 'confirmed': 273346, 'active': 16529, 'deaths': 4235, 'recovered': 252582, 'latitude': 55.1694, 'longitude': 23.8813, 'last_update': 1622197243000}, {'id': '60', 'country': 'Ethiopia', 'confirmed': 270527, 'active': 31974, 'deaths': 4127, 'recovered': 234426, 'latitude': 9.145, 'longitude': 40.4897, 'last_update': 1622197243000}, {'id': '54', 'country': 'Egypt', 'confirmed': 258407, 'active': 54027, 'deaths': 14904, 'recovered': 189476, 'latitude': 26.820553, 'longitude': 30.802498, 'last_update': 1622197243000}, {'id': '118', 'country': 'Moldova', 'confirmed': 254985, 'active': 1757, 'deaths': 6093, 'recovered': 247135, 'latitude': 47.4116, 'longitude': 28.3699, 'last_update': 1622197243000}, {'id': '84', 'country': 'Ireland', 'confirmed': 254870, 'active': 226565, 'deaths': 4941, 'recovered': 23364, 'latitude': 53.1424, 'longitude': -7.6921, 'last_update': 1622197243000}, {'id': '159', 'country': 'Slovenia', 'confirmed': 252848, 'active': 4797, 'deaths': 4366, 'recovered': 243685, 'latitude': 46.1512, 'longitude': 14.9955, 'last_update': 1622197243000}, {'id': '71', 'country': 'Guatemala', 'confirmed': 251336, 'active': 12384, 'deaths': 8070, 'recovered': 230882, 'latitude': 15.7835, 'longitude': -90.2308, 'last_update': 1622197243000}, {'id': '77', 'country': 'Honduras', 'confirmed': 235599, 'active': 145117, 'deaths': 6259, 'recovered': 84223, 'latitude': 15.2, 'longitude': -86.2419, 'last_update': 1622197243000}, {'id': '13', 'country': 'Bahrain', 'confirmed': 229468, 'active': 26878, 'deaths': 907, 'recovered': 201683, 'latitude': 26.0275, 'longitude': 50.55, 'last_update': 1622197243000}, {'id': '188', 'country': 'Venezuela', 'confirmed': 228828, 'active': 14964, 'deaths': 2576, 'recovered': 211288, 'latitude': 6.4238, 'longitude': -66.5897, 'last_update': 1622197243000}, {'id': '8', 'country': 'Armenia', 'confirmed': 222513, 'active': 5524, 'deaths': 4423, 'recovered': 212566, 'latitude': 40.0691, 'longitude': 45.0382, 'last_update': 1622197243000}, {'id': '142', 'country': 'Qatar', 'confirmed': 216683, 'active': 4083, 'deaths': 552, 'recovered': 212048, 'latitude': 25.3548, 'longitude': 51.1839, 'last_update': 1622197243000}, {'id': '133', 'country': 'Oman', 'confirmed': 213784, 'active': 14401, 'deaths': 2303, 'recovered': 197080, 'latitude': 21.512583, 'longitude': 55.923255, 'last_update': 1622197243000}, {'id': '22', 'country': 'Bosnia and Herzegovina', 'confirmed': 203762, 'active': 20942, 'deaths': 9194, 'recovered': 173626, 'latitude': 43.9159, 'longitude': 17.6791, 'last_update': 1622197243000}, {'id': '102', 'country': 'Libya', 'confirmed': 184472, 'active': 10351, 'deaths': 3115, 'recovered': 171006, 'latitude': 26.3351, 'longitude': 17.228331, 'last_update': 1622197243000}, {'id': '165', 'country': 'Sri Lanka', 'confirmed': 174861, 'active': 29747, 'deaths': 1325, 'recovered': 143789, 'latitude': 7.873054, 'longitude': 80.771797, 'last_update': 1622197243000}, {'id': '91', 'country': 'Kenya', 'confirmed': 169697, 'active': 50601, 'deaths': 3108, 'recovered': 115988, 'latitude': -0.0236, 'longitude': 37.9062, 'last_update': 1622197243000}, {'id': '130', 'country': 'Nigeria', 'confirmed': 166191, 'active': 7585, 'deaths': 2071, 'recovered': 156535, 'latitude': 9.082, 'longitude': 8.6753, 'last_update': 1622197243000}, {'id': '131', 'country': 'North Macedonia', 'confirmed': 155169, 'active': 2499, 'deaths': 5369, 'recovered': 147301, 'latitude': 41.6086, 'longitude': 21.7453, 'last_update': 1622197243000}, {'id': '174', 'country': 'Thailand', 'confirmed': 144976, 'active': 117149, 'deaths': 954, 'recovered': 26873, 'latitude': 15.870032, 'longitude': 100.992541, 'last_update': 1622197243000}, {'id': '28', 'country': 'Burma', 'confirmed': 143414, 'active': 7929, 'deaths': 3216, 'recovered': 132269, 'latitude': 21.9162, 'longitude': 95.956, 'last_update': 1622197243000}, {'id': '93', 'country': 'Korea, South', 'confirmed': 138898, 'active': 8191, 'deaths': 1946, 'recovered': 128761, 'latitude': 35.907757, 'longitude': 127.766922, 'last_update': 1622197243000}, {'id': '45', 'country': 'Cuba', 'confirmed': 137730, 'active': 6611, 'deaths': 921, 'recovered': 130198, 'latitude': 21.521757, 'longitude': -77.781167, 'last_update': 1622197243000}, {'id': '98', 'country': 'Latvia', 'confirmed': 132612, 'active': 6106, 'deaths': 2359, 'recovered': 124147, 'latitude': 56.8796, 'longitude': 24.6032, 'last_update': 1622197243000}, {'id': '2', 'country': 'Albania', 'confirmed': 132264, 'active': 775, 'deaths': 2447, 'recovered': 129042, 'latitude': 41.1533, 'longitude': 20.1683, 'last_update': 1622197243000}, {'id': '58', 'country': 'Estonia', 'confirmed': 129297, 'active': 5508, 'deaths': 1247, 'recovered': 122542, 'latitude': 58.5953, 'longitude': 25.0136, 'last_update': 1622197243000}, {'id': '3', 'country': 'Algeria', 'confirmed': 127926, 'active': 35438, 'deaths': 3448, 'recovered': 89040, 'latitude': 28.0339, 'longitude': 1.6596, 'last_update': 1622197243000}, {'id': '132', 'country': 'Norway', 'confirmed': 124071, 'active': 105290, 'deaths': 783, 'recovered': 17998, 'latitude': 60.472, 'longitude': 8.4689, 'last_update': 1622197243000}, {'id': '94', 'country': 'Kosovo', 'confirmed': 106928, 'active': 2790, 'deaths': 2247, 'recovered': 101891, 'latitude': 42.602636, 'longitude': 20.902977, 'last_update': 1622197243000}, {'id': '96', 'country': 'Kyrgyzstan', 'confirmed': 103866, 'active': 4536, 'deaths': 1788, 'recovered': 97542, 'latitude': 41.20438, 'longitude': 74.766098, 'last_update': 1622197243000}, {'id': '37', 'country': 'China', 'confirmed': 102932, 'active': 379, 'deaths': 4846, 'recovered': 97707, 'latitude': 30.5928, 'longitude': 114.3055, 'last_update': 1622197243000}, {'id': '186', 'country': 'Uzbekistan', 'confirmed': 99580, 'active': 3643, 'deaths': 687, 'recovered': 95250, 'latitude': 41.377491, 'longitude': 64.585262, 'last_update': 1622197243000}, {'id': '121', 'country': 'Montenegro', 'confirmed': 99477, 'active': 973, 'deaths': 1578, 'recovered': 96926, 'latitude': 42.708678, 'longitude': 19.37439, 'last_update': 1622197243000}, {'id': '192', 'country': 'Zambia', 'confirmed': 93947, 'active': 1351, 'deaths': 1275, 'recovered': 91321, 'latitude': -13.133897, 'longitude': 27.849332, 'last_update': 1622197243000}, {'id': '68', 'country': 'Ghana', 'confirmed': 93723, 'active': 1197, 'deaths': 783, 'recovered': 91743, 'latitude': 7.9465, 'longitude': -1.0232, 'last_update': 1622197243000}, {'id': '62', 'country': 'Finland', 'confirmed': 92062, 'active': 45116, 'deaths': 946, 'recovered': 46000, 'latitude': 61.9241, 'longitude': 25.7482, 'last_update': 1622197243000}, {'id': '32', 'country': 'Cameroon', 'confirmed': 77982, 'active': 41451, 'deaths': 1270, 'recovered': 35261, 'latitude': 3.848, 'longitude': 11.5021, 'last_update': 1622197243000}, {'id': '55', 'country': 'El Salvador', 'confirmed': 72821, 'active': 2566, 'deaths': 2237, 'recovered': 68018, 'latitude': 13.7942, 'longitude': -88.8965, 'last_update': 1622197243000}, {'id': '46', 'country': 'Cyprus', 'confirmed': 72234, 'active': 32816, 'deaths': 357, 'recovered': 39061, 'latitude': 35.1264, 'longitude': 33.4299, 'last_update': 1622197243000}, {'id': '123', 'country': 'Mozambique', 'confirmed': 70673, 'active': 612, 'deaths': 834, 'recovered': 69227, 'latitude': -18.665695, 'longitude': 35.529562, 'last_update': 1622197243000}, {'id': '105', 'country': 'Luxembourg', 'confirmed': 69749, 'active': 1112, 'deaths': 813, 'recovered': 67824, 'latitude': 49.8153, 'longitude': 6.1296, 'last_update': 1622197243000}, {'id': '1', 'country': 'Afghanistan', 'confirmed': 68366, 'active': 8378, 'deaths': 2869, 'recovered': 57119, 'latitude': 33.93911, 'longitude': 67.709953, 'last_update': 1622197243000}, {'id': '157', 'country': 'Singapore', 'confirmed': 61940, 'active': 536, 'deaths': 32, 'recovered': 61372, 'latitude': 1.2833, 'longitude': 103.8333, 'last_update': 1622197243000}, {'id': '110', 'country': 'Maldives', 'confirmed': 60943, 'active': 25427, 'deaths': 151, 'recovered': 35365, 'latitude': 3.2028, 'longitude': 73.2207, 'last_update': 1622197243000}, {'id': '120', 'country': 'Mongolia', 'confirmed': 55852, 'active

In [ ]:
#List Countries
countries = covid.list_countries()
print(countries)

[{'id': '180', 'name': 'US'}, {'id': '80', 'name': 'India'}, {'id': '24', 'name': 'Brazil'}, {'id': '63', 'name': 'France'}, {'id': '179', 'name': 'Turkey'}, {'id': '144', 'name': 'Russia'}, {'id': '184', 'name': 'United Kingdom'}, {'id': '86', 'name': 'Italy'}, {'id': '67', 'name': 'Germany'}, {'id': '7', 'name': 'Argentina'}, {'id': '164', 'name': 'Spain'}, {'id': '38', 'name': 'Colombia'}, {'id': '82', 'name': 'Iran'}, {'id': '140', 'name': 'Poland'}, {'id': '116', 'name': 'Mexico'}, {'id': '182', 'name': 'Ukraine'}, {'id': '138', 'name': 'Peru'}, {'id': '81', 'name': 'Indonesia'}, {'id': '126', 'name': 'Netherlands'}, {'id': '47', 'name': 'Czechia'}, {'id': '162', 'name': 'South Africa'}, {'id': '33', 'name': 'Canada'}, {'id': '36', 'name': 'Chile'}, {'id': '139', 'name': 'Philippines'}, {'id': '83', 'name': 'Iraq'}, {'id': '143', 'name': 'Romania'}, {'id': '168', 'name': 'Sweden'}, {'id': '17', 'name': 'Belgium'}, {'id': '134', 'name': 'Pakistan'}, {'id': '141', 'name': 'Portugal'}, {'id': '85', 'name': 'Israel'}, {'id': '78', 'name': 'Hungary'}, {'id': '14', 'name': 'Bangladesh'}, {'id': '88', 'name': 'Japan'}, {'id': '89', 'name': 'Jordan'}, {'id': '154', 'name': 'Serbia'}, {'id': '169', 'name': 'Switzerland'}, {'id': '10', 'name': 'Austria'}, {'id': '183', 'name': 'United Arab Emirates'}, {'id': '109', 'name': 'Malaysia'}, {'id': '125', 'name': 'Nepal'}, {'id': '99', 'name': 'Lebanon'}, {'id': '122', 'name': 'Morocco'}, {'id': '152', 'name': 'Saudi Arabia'}, {'id': '90', 'name': 'Kazakhstan'}, {'id': '53', 'name': 'Ecuador'}, {'id': '26', 'name': 'Bulgaria'}, {'id': '69', 'name': 'Greece'}, {'id': '16', 'name': 'Belarus'}, {'id': '158', 'name': 'Slovakia'}, {'id': '135', 'name': 'Panama'}, {'id': '21', 'name': 'Bolivia'}, {'id': '44', 'name': 'Croatia'}, {'id': '137', 'name': 'Paraguay'}, {'id': '66', 'name': 'Georgia'}, {'id': '178', 'name': 'Tunisia'}, {'id': '11', 'name': 'Azerbaijan'}, {'id': '42', 'name': 'Costa Rica'}, {'id': '190', 'name': 'West Bank and Gaza'}, {'id': '95', 'name': 'Kuwait'}, {'id': '52', 'name': 'Dominican Republic'}, {'id': '185', 'name': 'Uruguay'}, {'id': '48', 'name': 'Denmark'}, {'id': '104', 'name': 'Lithuania'}, {'id': '60', 'name': 'Ethiopia'}, {'id': '54', 'name': 'Egypt'}, {'id': '118', 'name': 'Moldova'}, {'id': '84', 'name': 'Ireland'}, {'id': '159', 'name': 'Slovenia'}, {'id': '71', 'name': 'Guatemala'}, {'id': '77', 'name': 'Honduras'}, {'id': '13', 'name': 'Bahrain'}, {'id': '188', 'name': 'Venezuela'}, {'id': '8', 'name': 'Armenia'}, {'id': '142', 'name': 'Qatar'}, {'id': '133', 'name': 'Oman'}, {'id': '22', 'name': 'Bosnia and Herzegovina'}, {'id': '102', 'name': 'Libya'}, {'id': '165', 'name': 'Sri Lanka'}, {'id': '91', 'name': 'Kenya'}, {'id': '130', 'name': 'Nigeria'}, {'id': '131', 'name': 'North Macedonia'}, {'id': '174', 'name': 'Thailand'}, {'id': '28', 'name': 'Burma'}, {'id': '93', 'name': 'Korea, South'}, {'id': '45', 'name': 'Cuba'}, {'id': '98', 'name': 'Latvia'}, {'id': '2', 'name': 'Albania'}, {'id': '58', 'name': 'Estonia'}, {'id': '3', 'name': 'Algeria'}, {'id': '132', 'name': 'Norway'}, {'id': '94', 'name': 'Kosovo'}, {'id': '96', 'name': 'Kyrgyzstan'}, {'id': '37', 'name': 'China'}, {'id': '186', 'name': 'Uzbekistan'}, {'id': '121', 'name': 'Montenegro'}, {'id': '192', 'name': 'Zambia'}, {'id': '68', 'name': 'Ghana'}, {'id': '62', 'name': 'Finland'}, {'id': '32', 'name': 'Cameroon'}, {'id': '55', 'name': 'El Salvador'}, {'id': '46', 'name': 'Cyprus'}, {'id': '123', 'name': 'Mozambique'}, {'id': '105', 'name': 'Luxembourg'}, {'id': '1', 'name': 'Afghanistan'}, {'id': '157', 'name': 'Singapore'}, {'id': '110', 'name': 'Maldives'}, {'id': '120', 'name': 'Mongolia'}, {'id': '124', 'name': 'Namibia'}, {'id': '23', 'name': 'Botswana'}, {'id': '87', 'name': 'Jamaica'}, {'id': '43', 'name': "Cote d'Ivoire"}, {'id': '181', 'name': 'Uganda'}, {'id': '153', 'name': 'Senegal'}, {'id': '107', 'name': 'Madagascar'}, {'id': '193', 'name': 'Zimbabwe'}, {'id': '166', 'name': 'Sudan'}, {'id': '108', 'name': 'Malawi'}, {'id': '5', 'name': 'Angola'}, {'id': '41', 'name': 'Congo (Kinshasa)'}, {'id': '112', 'name': 'Malta'}, {'id': '9', 'name': 'Australia'}, {'id': '30', 'name': 'Cabo Verde'}, {'id': '31', 'name': 'Cambodia'}, {'id': '145', 'name': 'Rwanda'}, {'id': '170', 'name': 'Syria'}, {'id': '64', 'name': 'Gabon'}, {'id': '72', 'name': 'Guinea'}, {'id': '177', 'name': 'Trinidad and Tobago'}, {'id': '114', 'name': 'Mauritania'}, {'id': '59', 'name': 'Eswatini'}, {'id': '74', 'name': 'Guyana'}, {'id': '136', 'name': 'Papua New Guinea'}, {'id': '161', 'name': 'Somalia'}, {'id': '111', 'name': 'Mali'}, {'id': '75', 'name': 'Haiti'}, {'id': '167', 'name': 'Suriname'}, {'id': '4', 'name': 'Andorra'}, {'id': '27', 'name': 'Burkina Faso'}, {'id': '176', 'name': 'Togo'}, {'id': '172', 'name': 'Tajikistan'}, {'id': '18', 'name': 'Belize'}, {'id': '40', 'name': 'Congo (Brazzaville)'}, {'id': '12', 'name': 'Bahamas'}, {'id': '50', 'name': 'Djibouti'}, {'id': '155', 'name': 'Seychelles'}, {'id': '100', 'name': 'Lesotho'}, {'id': '163', 'name': 'South Sudan'}, {'id': '56', 'name': 'Equatorial Guinea'}, {'id': '19', 'name': 'Benin'}, {'id': '128', 'name': 'Nicaragua'}, {'id': '34', 'name': 'Central African Republic'}, {'id': '171', 'name': 'Taiwan*'}, {'id': '191', 'name': 'Yemen'}, {'id': '79', 'name': 'Iceland'}, {'id': '175', 'name': 'Timor-Leste'}, {'id': '189', 'name': 'Vietnam'}, {'id': '65', 'name': 'Gambia'}, {'id': '129', 'name': 'Niger'}, {'id': '150', 'name': 'San Marino'}, {'id': '147', 'name': 'Saint Lucia'}, {'id': '35', 'name': 'Chad'}, {'id': '29', 'name': 'Burundi'}, {'id': '156', 'name': 'Sierra Leone'}, {'id': '57', 'name': 'Eritrea'}, {'id': '15', 'name': 'Barbados'}, {'id': '39', 'name': 'Comoros'}, {'id': '73', 'name': 'Guinea-Bissau'}, {'id': '103', 'name': 'Liechtenstein'}, {'id': '127', 'name': 'New Zealand'}, {'id': '119', 'name': 'Monaco'}, {'id': '151', 'name': 'Sao Tome and Principe'}, {'id': '101', 'name': 'Liberia'}, {'id': '148', 'name': 'Saint Vincent and the Grenadines'}, {'id': '97', 'name': 'Laos'}, {'id': '20', 'name': 'Bhutan'}, {'id': '115', 'name': 'Mauritius'}, {'id': '6', 'name': 'Antigua and Barbuda'}, {'id': '49', 'name': 'Diamond Princess'}, {'id': '173', 'name': 'Tanzania'}, {'id': '61', 'name': 'Fiji'}, {'id': '25', 'name': 'Brunei'}, {'id': '51', 'name': 'Dominica'}, {'id': '70', 'name': 'Grenada'}, {'id': '146', 'name': 'Saint Kitts and Nevis'}, {'id': '76', 'name': 'Holy See'}, {'id': '160', 'name': 'Solomon Islands'}, {'id': '106', 'name': 'MS Zaandam'}, {'id': '113', 'name': 'Marshall Islands'}, {'id': '187', 'name': 'Vanuatu'}, {'id': '149', 'name': 'Samoa'}, {'id': '92', 'name': 'Kiribati'}, {'id': '117', 'name': 'Micronesia'}]

In [ ]:
#Get Status By Country ID
italy_cases = covid.get_status_by_country_id(115)

print(italy_cases)

{'id': '115', 'country': 'Mauritius', 'confirmed': 1344, 'active': 146, 'deaths': 17, 'recovered': 1181, 'latitude': -20.348404, 'longitude': 57.552152, 'last_update': 1622197243000}

In [ ]:
#Get Status By Country Name
italy_cases = covid.get_status_by_country_name("italy")
print(italy_cases)

{'id': '86', 'country': 'Italy', 'confirmed': 4205970, 'active': 253193, 'deaths': 125793, 'recovered': 3826984, 'latitude': 41.8719, 'longitude': 12.5674, 'last_update': 1622197243000}

In [ ]:
#Get Total Active cases
active = covid.get_total_active_cases()
#Get Total Confirmed cases
confirmed = covid.get_total_confirmed_cases()
#Get Total Recovered cases
recovered = covid.get_total_recovered()
#Get Total Deaths
deaths = covid.get_total_deaths()

print(active)
print(confirmed)
print(recovered)
print(deaths)

26750763
169021406
106132619
3512719

COVID TESTY :  Worldometers.info

In [ ]:
#Getting data from Worldometers.info
#worldometers

covid = Covid(source="worldometers")
#Get Data
covid.get_data()

In [ ]:
#Get Status By Country Name
#covid.get_status_by_country_name("italy")
covid.get_status_by_country_name("poland")

{'active': 162327,
 'confirmed': 2870595,
 'country': 'Poland',
 'critical': 805,
 'deaths': 73557,
 'new_cases': 946,
 'new_deaths': 117,
 'population': Decimal('37809132'),
 'recovered': 2634711,
 'total_cases_per_million': Decimal('75923'),
 'total_deaths_per_million': Decimal('1945'),
 'total_tests': 15765052,
 'total_tests_per_million': Decimal('0')}

In [ ]:
#List Countries
countries = covid.list_countries()
print(countries)

['north america', 'asia', 'south america', 'europe', 'africa', 'oceania', '', 'world', 'usa', 'india', 'brazil', 'france', 'turkey', 'russia', 'uk', 'italy', 'germany', 'argentina', 'spain', 'colombia', 'iran', 'poland', 'mexico', 'ukraine', 'peru', 'indonesia', 'czechia', 'south africa', 'netherlands', 'canada', 'chile', 'philippines', 'iraq', 'romania', 'sweden', 'belgium', 'pakistan', 'portugal', 'israel', 'hungary', 'bangladesh', 'jordan', 'japan', 'serbia', 'switzerland', 'austria', 'uae', 'malaysia', 'nepal', 'lebanon', 'morocco', 'saudi arabia', 'ecuador', 'bulgaria', 'greece', 'belarus', 'slovakia', 'kazakhstan', 'panama', 'bolivia', 'croatia', 'paraguay', 'georgia', 'tunisia', 'azerbaijan', 'costa rica', 'palestine', 'kuwait', 'dominican republic', 'uruguay', 'denmark', 'lithuania', 'ethiopia', 'ireland', 'egypt', 'moldova', 'slovenia', 'guatemala', 'honduras', 'bahrain', 'venezuela', 'armenia', 'qatar', 'oman', 'bosnia and herzegovina', 'libya', 'sri lanka', 'kenya', 'nigeria', 'north macedonia', 'thailand', 'myanmar', 's. korea', 'cuba', 'latvia', 'albania', 'estonia', 'algeria', 'norway', 'kyrgyzstan', 'uzbekistan', 'montenegro', 'zambia', 'ghana', 'finland', 'cameroon', 'el salvador', 'cyprus', 'mozambique', 'afghanistan', 'luxembourg', 'singapore', 'maldives', 'mongolia', 'namibia', 'botswana', 'jamaica', 'ivory coast', 'uganda', 'senegal', 'madagascar', 'zimbabwe', 'sudan', 'malawi', 'angola', 'drc', 'malta', 'australia', 'cabo verde', 'cambodia', 'rwanda', 'réunion', 'syria', 'gabon', 'french guiana', 'guinea', 'trinidad and tobago', 'mayotte', 'mauritania', 'french polynesia', 'eswatini', 'guyana', 'guadeloupe', 'papua new guinea', 'somalia', 'mali', 'haiti', 'suriname', 'andorra', 'burkina faso', 'togo', 'tajikistan', 'belize', 'curaçao', 'martinique', 'hong kong', 'congo', 'bahamas', 'djibouti', 'seychelles', 'aruba', 'lesotho', 'south sudan', 'equatorial guinea', 'benin', 'nicaragua', 'taiwan', 'car', 'yemen', 'iceland', 'timor-leste', 'vietnam', 'gambia', 'niger', 'san marino', 'saint lucia', 'chad', 'burundi', 'gibraltar', 'sierra leone', 'channel islands', 'eritrea', 'barbados', 'comoros', 'guinea-bissau', 'liechtenstein', 'new zealand', 'monaco', 'bermuda', 'turks and caicos', 'sint maarten', 'sao tome and principe', 'liberia', 'st. vincent grenadines', 'saint martin', 'laos', 'caribbean netherlands', 'isle of man', 'bhutan', 'mauritius', 'antigua and barbuda', 'st. barth', 'diamond princess', 'faeroe islands', 'cayman islands', 'tanzania', 'wallis and futuna', 'fiji', 'british virgin islands', 'brunei', 'dominica', 'grenada', 'new caledonia', 'anguilla', 'saint kitts and nevis', 'falkland islands', 'macao', 'greenland', 'vatican city', 'saint pierre miquelon', 'montserrat', 'solomon islands', 'western sahara', 'ms zaandam', 'vanuatu', 'marshall islands', 'samoa', 'saint helena', 'micronesia', 'china']

In [ ]:

#Get Total Active cases
active = covid.get_total_active_cases()
#Get Total Confirmed cases
confirmed = covid.get_total_confirmed_cases()
#Get Total Recovered cases
recovered = covid.get_total_recovered()
#Get Total Deaths
deaths = covid.get_total_deaths()

print(active)
print(confirmed)
print(recovered)
print(deaths)

14735578
169711179
151448516
3527085

BIBLIOTEKA covid_daily TESTY

In [ ]:
#https://pypi.org/project/covid-daily/

In [ ]:
pip install covid_daily

Collecting covid_daily
  Downloading https://files.pythonhosted.org/packages/a9/66/308c469076dff77912731319b99171529fa20003db2d4013bb91da3211cf/covid_daily-1.3.0.tar.gz
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from covid_daily) (4.5.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from covid_daily) (1.19.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from covid_daily) (1.1.5)
Collecting Unidecode
  Downloading https://files.pythonhosted.org/packages/9e/25/723487ca2a52ebcee88a34d7d1f5a4b80b793f179ee0f62d5371938dfa01/Unidecode-1.2.0-py2.py3-none-any.whl (241kB)
     |████████████████████████████████| 245kB 2.9MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from covid_daily) (2.23.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->covid_daily) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas->covid_daily) (2018.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->covid_daily) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->covid_daily) (1.25.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->covid_daily) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->covid_daily) (2.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->covid_daily) (1.14.0)
Building wheels for collected packages: covid-daily
  Building wheel for covid-daily (setup.py) ... done
  Created wheel for covid-daily: filename=covid_daily-1.3.0-cp37-none-any.whl size=11153 sha256=bdfd54d3c62ca3eea7dcf25bcb66f203301684a3942483a398761aaadc2c97b9
  Stored in directory: /root/.cache/pip/wheels/31/1f/c1/feee03a0818d343f754e87ab4b52fba8e5cb25578d89513bc2
Successfully built covid-daily
Installing collected packages: Unidecode, covid-daily
Successfully installed Unidecode-1.2.0 covid-daily-1.3.0

In [ ]:
import covid_daily

overview = covid_daily.overview(as_json=False)

print(overview.head())

overview

  Country,Other  TotalCases  ...  New Deaths/1M pop  Active Cases/1M pop
0         World   169715540  ...                  0                    0
1           USA    33999680  ...                  0                17100
2         India    27555457  ...                  0                 1683
3        Brazil    16342162  ...                  0                 5138
4        France     5635629  ...                  0                 3703

[5 rows x 20 columns]

    Country,Other  TotalCases  ...  New Deaths/1M pop  Active Cases/1M pop
0           World   169715540  ...                  0                    0
1             USA    33999680  ...                  0                17100
2           India    27555457  ...                  0                 1683
3          Brazil    16342162  ...                  0                 5138
4          France     5635629  ...                  0                 3703
..            ...         ...  ...                ...                  ...
219         Samoa           3  ...                  0                    0
220  Saint Helena           2  ...                  0                    0
221    Micronesia           1  ...                  0                    0
222         China       91045  ...                  0                    0
223         Total   169715540  ...                  0                    0

[224 rows x 20 columns]

In [ ]:
import covid_daily

data = covid_daily.data(country='spain', chart='total-currently-infected-linear', as_json=False)

print(data.head())

RuntimeError: ignored

BIBLIOTEKA COVID-19-Cases TESTY

In [ ]:
https://pypi.org/project/COVID-19-Cases/

In [ ]:
pip install COVID-19-Cases

Collecting COVID-19-Cases
  Downloading https://files.pythonhosted.org/packages/c1/4f/7aebf5b70c6065986c850d41b1a3e70464c7561fbb14e75e16e70ebab409/COVID_19_Cases-0.0.3-py3-none-any.whl
Collecting soupsieve==2.0
  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Collecting autopep8==1.5
  Downloading https://files.pythonhosted.org/packages/12/55/7b07585ca0c30e5b216e4d627f82f96f1a7e82d2dd727b1f926cb3f3d58b/autopep8-1.5.tar.gz (116kB)
     |████████████████████████████████| 122kB 4.9MB/s
Collecting pycodestyle==2.5.0
  Downloading https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl (51kB)
     |████████████████████████████████| 51kB 5.5MB/s
Collecting pylint==2.4.4
  Downloading https://files.pythonhosted.org/packages/e9/59/43fc36c5ee316bb9aeb7cf5329cdbdca89e5749c34d5602753827c0aa2dc/pylint-2.4.4-py3-none-any.whl (302kB)
     |████████████████████████████████| 307kB 25.8MB/s
Collecting idna==2.9
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 7.0MB/s
Collecting mccabe==0.6.1
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Requirement already satisfied: requests==2.23.0 in /usr/local/lib/python3.7/dist-packages (from COVID-19-Cases) (2.23.0)
Collecting lazy-object-proxy==1.4.3
  Downloading https://files.pythonhosted.org/packages/23/f8/69df5a663b59512eb9f9b84e7f203c48c7a933e460316e9ebf4db2871ae0/lazy_object_proxy-1.4.3-cp37-cp37m-manylinux1_x86_64.whl (56kB)
     |████████████████████████████████| 61kB 7.6MB/s
Collecting certifi==2019.11.28
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
     |████████████████████████████████| 163kB 30.2MB/s
Collecting lxml==4.5.0
  Downloading https://files.pythonhosted.org/packages/85/9e/93e2c3af278c7c8b6826666bbcb145af2829bd761c3b329e51cd6343836c/lxml-4.5.0-cp37-cp37m-manylinux1_x86_64.whl (5.7MB)
     |████████████████████████████████| 5.7MB 10.7MB/s
Collecting six==1.14.0
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Requirement already satisfied: chardet==3.0.4 in /usr/local/lib/python3.7/dist-packages (from COVID-19-Cases) (3.0.4)
Collecting wrapt==1.11.2
  Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting astroid==2.3.3
  Downloading https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl (205kB)
     |████████████████████████████████| 215kB 34.0MB/s
Collecting urllib3==1.25.8
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
     |████████████████████████████████| 133kB 40.6MB/s
Collecting beautifulsoup4==4.8.2
  Downloading https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl (106kB)
     |████████████████████████████████| 112kB 42.4MB/s
Collecting isort==4.3.21
  Downloading https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 6.1MB/s
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8"
  Downloading https://files.pythonhosted.org/packages/65/b3/573d2f1fecbbe8f82a8d08172e938c247f99abe1be3bef3da2efaa3810bf/typed_ast-1.4.3-cp37-cp37m-manylinux1_x86_64.whl (743kB)
     |████████████████████████████████| 747kB 26.8MB/s
Building wheels for collected packages: autopep8, wrapt
  Building wheel for autopep8 (setup.py) ... done
  Created wheel for autopep8: filename=autopep8-1.5-py2.py3-none-any.whl size=43267 sha256=d7c205cc561e02af44270959475736bff99ff71ab3d689044ef46b4e5aed929b
  Stored in directory: /root/.cache/pip/wheels/2b/dc/d5/e4bc37df332b7a88022bc79d6cdccb79068fdc1620d86afc3a
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.11.2-cp37-cp37m-linux_x86_64.whl size=68454 sha256=cba498ceb6f8921f63415ebfcf29fed0d01d81bf99af02ce569824a21f974bd2
  Stored in directory: /root/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built autopep8 wrapt
ERROR: tensorflow 2.5.0 has requirement six~=1.15.0, but you'll have six 1.14.0 which is incompatible.
ERROR: tensorflow 2.5.0 has requirement wrapt~=1.12.1, but you'll have wrapt 1.11.2 which is incompatible.
ERROR: google-colab 1.0.0 has requirement six~=1.15.0, but you'll have six 1.14.0 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
Installing collected packages: soupsieve, pycodestyle, autopep8, mccabe, six, lazy-object-proxy, wrapt, typed-ast, astroid, isort, pylint, idna, certifi, lxml, urllib3, beautifulsoup4, COVID-19-Cases
  Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Found existing installation: wrapt 1.12.1
    Uninstalling wrapt-1.12.1:
      Successfully uninstalled wrapt-1.12.1
  Found existing installation: idna 2.10
    Uninstalling idna-2.10:
      Successfully uninstalled idna-2.10
  Found existing installation: certifi 2020.12.5
    Uninstalling certifi-2020.12.5:
      Successfully uninstalled certifi-2020.12.5
  Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
  Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
Successfully installed COVID-19-Cases-0.0.3 astroid-2.3.3 autopep8-1.5 beautifulsoup4-4.8.2 certifi-2019.11.28 idna-2.9 isort-4.3.21 lazy-object-proxy-1.4.3 lxml-4.5.0 mccabe-0.6.1 pycodestyle-2.5.0 pylint-2.4.4 six-1.14.0 soupsieve-2.0 typed-ast-1.4.3 urllib3-1.25.8 wrapt-1.11.2

In [ ]:
import covid19cases as covid

#get_global_cases()
#Get the latest cases of all affected countries if there's no parameter passed to the method. Else, it will fetch data of specific country.

#get_country_cases()
x = covid.get_country_cases("Philippines")

#Get the latest cases of all affected continents if there's no parameter passed to the method. Else, it will fetch data of specific continent.
#get_continent_cases()
y = covid.get_continent_cases("Asia")

print(x)
print(y)

x

y

{'#': '24', 'CountryOrRegion': 'Philippines', 'TotalCases': '1,209,154', 'NewCases': '+8,748', 'TotalDeaths': '20,566', 'NewDeaths': '+187', 'TotalRecovered': '1,134,818', 'NewRecovered': '+3,017', 'ActiveCases': '53,770', 'Critical': '1,704', 'CasesPerOneMillion': '485', 'DeathsPerOneMillion': '2', 'TotalTests': '13,197,470', 'TestsPerOneMillion': '119,009', 'Population': '110,894,418', 'Continent': 'Asia', '1 Caseevery X ppl': '92', '1 Deathevery X ppl': '5,392', '1 Testevery X ppl': '8', 'LastUpdated': 'May 28, 2021, 11:51 GMT'}
{'#': '', 'CountryOrRegion': 'Asia', 'TotalCases': '50,405,587', 'NewCases': '+69,458', 'TotalDeaths': '669,246', 'NewDeaths': '+1,171', 'TotalRecovered': '45,972,143', 'NewRecovered': '+61,032', 'ActiveCases': '3,764,198', 'Critical': '30,507', 'CasesPerOneMillion': '', 'DeathsPerOneMillion': '', 'TotalTests': '', 'TestsPerOneMillion': '', 'Population': '', 'Continent': 'Asia', '1 Caseevery X ppl': '', '1 Deathevery X ppl': '', '1 Testevery X ppl': '', 'LastUpdated': 'May 28, 2021, 11:51 GMT'}

{'#': '',
 '1 Caseevery X ppl': '',
 '1 Deathevery X ppl': '',
 '1 Testevery X ppl': '',
 'ActiveCases': '3,764,198',
 'CasesPerOneMillion': '',
 'Continent': 'Asia',
 'CountryOrRegion': 'Asia',
 'Critical': '30,507',
 'DeathsPerOneMillion': '',
 'LastUpdated': 'May 28, 2021, 11:51 GMT',
 'NewCases': '+69,458',
 'NewDeaths': '+1,171',
 'NewRecovered': '+61,032',
 'Population': '',
 'TestsPerOneMillion': '',
 'TotalCases': '50,405,587',
 'TotalDeaths': '669,246',
 'TotalRecovered': '45,972,143',
 'TotalTests': ''}

INNE

In [ ]:
#https://libraries.io/pypi/worldometer

In [ ]:
import worldometer

x1 = worldometer.current_world_population()
#{'current_world_population': 7845085923}

#x2= worldometer.tweets_sent_today()
{'tweets_sent_today': 4539558}

#x3 = worldometer.get_metric_of(label='computers_produced_this_year')
{'computers_produced_this_year': 27760858}

print(x1)
print(x2)
print(x3)

Exception: ignored

In [ ]:
>>> from worldometer import Worldometer
>>> w = Worldometer()

>>> w.what_is_here()
{'categories': 8, 'labels': 63, 'metrics': 63}

>>> w.categories()
[   
    'world_population',
    'government_and_economics',
    'society_and_media',
    ...  # compressed
]

>>> w.metrics_labels()
[   
    'current_world_population',
    'births_this_year',
    'births_today',
    'deaths_this_year',
    'deaths_today',
    'net_population_growth_this_year',
    ...  # compressed
]

>>> w.metrics()
[   
    7845087963,
    15741371,
    5676,
    6608605,
    2383,
    9132766,
    ...  # compressed
]

>>> w.metrics_with_labels()
{   
    'abortions_this_year': 4785492,
    'bicycles_produced_this_year': 17070566,
    'births_this_year': 15741371,
    'births_today': 5676,
    'blog_posts_written_today': 110171,
    'cars_produced_this_year': 8999185,
    'cellular_phones_sold_today': 98846,
    ...: ...  # compressed
}